Vocabulary_alt = {

    "21" : "Einundzwanzig",
    "672" : "sechshundertzweiundsiebzig",
    "A lot" : "Viel",
    "Actually" : "Eigentlich",
    "Add/Complete" : "Ergänzen",
    "Africa" : "Afrika",
    "Again" : "Wieder",
    "All right" : "Alles klar",
    "Alone" : "Allein",
    "Already" : "Schon",
    "Alright" : "In ordnung",
    "Also" : "Auch",
    "Always" : "Immer",
    "America" : "Amerika",
    "American" : "Amerikaner/in",        
    "Angry" : "Böse",
    "Annoy" : "Reizen",
    "Appeal" : "Gefallen",
    "April" : "April",
    "Arrange" : "Arrangieren",
    "Asia" : "Asien",
    "Ask" : "Fragen",
    "At" : "Zu",
    "August" : "August",
    "Australia" : "Australien",
    "Austria" : "Österreich",
    "Austrian" : "Österreicher/in",
    "Away" : "Weg",
    "Back (on the back)" : "Hinten",
    "Bad" : "Schlecht",
    "Be" : "Sein",
    "Beautiful" : "Schön",
    "Because" : "Denn",
    "Become" : "Werden",
    "Believe" : "Glauben",
    "Belong to" : "Gehören",
    "Big/tall" : "Groß",
    "Bite" : "Beißen",
    "Black" : "Schwarz",
    "Boring" : "Langweilig",
    "Both" : "Beide",
    "Bother" : "Stören",
    "Brasil" : "Brasilien",
    "Break" : "Brechen",
    "Breath" : "Atmen",
    "Bright" : "Hell",
    "Bring" : "Bringen",
    "Broken" : "Kaputt",
    "Brown" : "Braun",
    "Bulgaria" : "Bulgarien",
    "But" : "Aber",
    "Buy" : "Kaufen",
    "By bus" : "Mit dem bus",
    "Bye (telephone)" : "Auf wiederhören",
    "Calm" : "Ruhig",
    "Canada" : "Kanada",
    "Cancel" : "Stornieren",
    "Celebrate" : "Feiern",
    "Cheap" : "Billig",
    "Check, examine" : "Überprüfen",
    "China" : "China",
    "Choose" : "Wählen",
    "Clean (adj)" : "Sauber",
    "Clear (verb)" : "Klären",
    "Cloudy" : "Bewölkt",
    "Cold" : "Kalt",
    "Come" : "Kommen",
    "Comfortable" : "Bequem",
    "Cook (verb)" : "Kochen",
    "Cool" : "Kühl",
    "Correct" : "Richtig",
    "Cost (verb)" : "Kosten",
    "Create" : "Schaffen",
    "Cut (verb)" : "Schneiden",
    "Dance (verb)" : "Tanzen",
    "Dark" : "Dunkel",
    "Days of the week" : "Wochentage",
    "December" : "Dezember",
    "Decide/Determine" : "Entscheiden",
    "Deep" : "Tief",
    "Delicious" : "Lecker",
    "Denmark" : "Dänemark",
    "Destroy" : "Zerstören",
    "Die" : "Sterben",
    "Different" : "Verschieden",
    "Dirty" : "Schmutzig",
    "Discuss" : "Diskutieren",
    "Do" : "Tun",
    "Drive" : "Fahren",
    "Easy" : "Einfach",
    "Easy/light" : "Leicht",
    "Eat (for animals)" : "Fressen",
    "Eat (verb)" : "Essen",
    "Eight" : "Acht",
    "Eighteen" : "Achtzehn",
    "Eighty" : "Achtzig",
    "Elegant" : "Elegant",
    "Eleven" : "Elf",
    "Empty" : "Leer",
    "England" : "England",
    "English" : "Englisch",
    "Enough" : "Genug",
    "Equal" : "Gleich",
    "Every/everyone" : "Jede",
    "Everyone" : "Alle",
    "Everything" : "Alles",
    "Exactly" : "Genau",
    "Excited" : "Aufgeregt",
    "Exciting" : "Aufregend",
    "Excuse me (formal)" : "Entschuldigen Sie",
    "Excuse me (informal)" : "Entschuldigung",
    "Expect/await" : "Erwarten",
    "Expensive" : "Teuer",
    "Explain" : "Erklären",
    "Fall/Autumn" : "Fall",
    "False/Wrong" : "Falsch",
    "Fantastic" : "Fantastisch",
    "Far" : "Weit",
    "Fast" : "Schnell",
    "Fat" : "Dick",
    "February" : "Februar",
    "Feel" : "Empfinden",
    "Fetch" : "Holen",
    "Fifteen" : "Fünfzehn",
    "Fifty" : "Fünfzig",
    "Find" : "Finden",
    "First" : "Erste",
    "Fit (verb)" : "Passen",
    "Five" : "Fünf",
    "Fly" : "Fliegen",
    "Foggy" : "Neblig",
    "For" : "Für",
    "Forget" : "Vergessen",
    "Four" : "Vier",
    "Fourteen" : "Vierzehn",
    "Fourty" : "Vierzig",
    "France" : "Frankreich",
    "Free" : "Frei",
    "French" : "Französisch",
    "Fresh" : "Frisch",
    "From" : "Aus",
    "Funny" : "Lustig",
    "German" : "Deutsche/r",
    "Give" : "Geben",
    "Give (gift)" : "Schenken",
    "Go" : "Gehen",
    "Good" : "Gut",
    "Good day" : "Guten tag",
    "Good evening" : "Guten abend",
    "Good morning" : "Guten morgen",
    "Good night" : "Gute nacht",
    "Good-bye/See you again" : "Wiederschauen",
    "Good-bye (Informell)" : "Tschüss",
    "Good-bye (Formell)" : "Auf wiedersehen",
    "Gray" : "Grau",
    "Great" : "Toll",
    "Greece" : "Griechenland",
    "Green" : "Grün",
    "Grow" : "Wachsen",
    "Hang around" : "Hängen",
    "Happy" : "Glücklich",
    "Have" : "Haben",
    "Have to" : "Müssen",
    "He is" : "Er ist",
    "Healthy" : "Gesund",
    "Hear" : "Hören",
    "Heavy/difficult" : "Schwer",
    "Hello" : "Hallo",
    "Help (verb)" : "Helfen",
    "Here" : "Hier",
    "High" : "Hoch",
    "Horrify (verb)" : "Entsetzen",
    "Hot" : "Heiß",
    "How are you? (formal)" : "Wie geht es Ihnen?",
    "How are you? (informal)" : "Wie geht's dir?",
    "How many/much" : "Wie viel",
    "How old are you? (formal)" : "Wie alt sind Sie?",
    "Hundred" : "(ein)hundert",
    "I am" : "Ich bin",
    "I am okay" : "Mir geht's gut",
    "I am sorry" : "Es tut mir leid",
    "I beg your pardon" : "Wie bitte?",
    "I can't right now" : "Ich kann jetzt nicht",
    "I don't know" : "Ich weiß nicht",
    "I don't understand" : "Ich verstehe nicht",
    "I speak a bit of German" : "Ich spreche etwas Deutsch",
    "Imitate" : "Imitieren",
    "Immigrate" : "Immigrieren",
    "Important" : "Wichtag",
    "Interesting" : "Interessant",
    "Into" : "Ins",
    "Irak" : "Irak",
    "It is" : "Es ist",
    "Italy" : "Italien",
    "January" : "Januar",
    "Jog" : "Joggen",
    "July" : "Juli",
    "June" : "Juni",
    "Just a moment" : "Einen moment",
    "Know" : "Kennen",
    "Know (acquainted)" : "Wissen",
    "Late" : "Spät",
    "Lay/be Located (verb)" : "Liegen",
    "Learn" : "Lernen",
    "Leave" : "Verlassen",
    "Left" : "Links",
    "Lend" : "Leihen",
    "Like" : "Mögen",
    "Little (2)" : "Bisschen",
    "Live" : "Leben",
    "Long" : "Lang",
    "Look for" : "Suchen",
    "Lose" : "Verlieren",
    "Loud" : "Laut",
    "Love (verb)" : "Lieben",
    "Make" : "Machen",
    "March" : "März",
    "March (verb)" : "Marschieren",
    "May" : "Mai",
    "Maybe" : "Vielleicht",
    "Meet" : "Treffen",
    "Mexico" : "Mexiko",
    "Million" : "(ein)million",
    "Mr" : "Herr",
    "Name/Call" : "Nennen",
    "Need" : "Brauchen",
    "Nervous" : "Nervös",
    "Never" : "Nie",
    "New" : "Neu",
    "Next" : "Nächste",
    "Nice" : "Nett",
    "Nice to see you" : "Schön dich zu sehen",
    "Nine" : "Neun",
    "Nineteen" : "Neunzehn",
    "Ninety" : "Neunzig",
    "No idea" : "Keine ahnung",
    "No problem" : "Kein problem",
    "Nobody" : "Niemand",
    "North Amerika" : "Nordamerika",
    "November" : "November",
    "Now" : "Jetzt",
    "October" : "Oktober",
    "Of course" : "Natürlich",
    "Often" : "Oft",
    "Old" : "Alt",
    "Once again" : "Noch einmal",
    "One" : "Eins",
    "Only" : "Nur",
    "Open (adj)" : "Geöffnet",
    "Or" : "Oder",
    "Order (verb)" : "Bestellen",
    "Organize" : "Organisieren",
    "Over (there)" : "Drüben",
    "Paint" : "Malen",
    "Partner" : "Partner",    
    "Pay" : "Bezahlen",
    "Pay (verb)" : "Zahlen",
    
    #atras no deberia haber nouns
    
    "Perfect" : "Perfekt",
    
    
    "Photograph (verb)" : "Fotografieren",
    
    
    
    "Pilot" : "Pilot",
    "Pink" : "Rosa",
    "Pizza" : "Pizza",
    "Plane ticket" : "Flugticket",
    "Please" : "Bitte",
    "Please repeat (formal)" : "Bitte wiederholen Sie",
    "Poland" : "Polen",
    "Police officer" : "Polizist",
    "Polish" : "Polnisch",
    "Possible" : "Möglich",
    "Potato" : "Kartoffel",
    "Profession" : "Beruf",
    "Promise" : "Versprechen",
    "Protect" : "Schützen",
    "Put" : "Stellen",
    "Quiet" : "Leise",
    "Rain (noun)" : "Regen",
    "Reach" : "Reichen",
    "Read" : "Lesen",
    "Ready" : "Fertig",
    "Really" : "Wirklich",
    "Receive" : "Bekommen",
    "Recommend" : "Empfehlen",
    "Red" : "Rot",
    "Refrigerator" : "Kühlschrank",
    "Reside" : "Wohnen",
    "Restaurant" : "Restaurant",
    "Rice" : "Reis",
    "Rich" : "Reich",
    "Right" : "Rechts",
    "Right now" : "Gerade",
    "Ring" : "Ring",
    "River" : "Fluss",
    "Rome" : "Rom",
    "Room" : "Zimmer",
    "Roommate" : "Mitbewohner",
    "Round" : "Rund",
    "Run" : "Rennen",
    "Russia" : "Russland",
    "Russian" : "Russisch",
    "Sad" : "Traurig",
    "Sail (v)" : "Segeln",
    "Salad" : "Salat",
    "Salt" : "Salz",
    "Same (adj)" : "Gleich",
    "Sandwich" : "Butterbrot",
    "Saturday" : "Samstag",
    "Sausage" : "Wurst",
    "Say" : "Sagen",
    "Scarf" : "Schal",
    "Schedule" : "Fahrplan",
    "School" : "Schule",
    "Sea" : "Meer",
    "Secondary school" : "Gymnasium",
    "See" : "Sehen",
    "See you later" : "Bis später",
    "See you soon (Informal)" : "Bis bald",
    "Sell" : "Verkaufen",
    "Send (2nd verb)" : "Schicken",
    "Send (verb)" : "Senden",
    "September" : "September",
    "Seven" : "Sieben",
    "Seventeen" : "Siebzehn",
    "Seventy" : "Siebzig",
    "She is" : "Sie ist",
    "Shirt" : "Hemd",
    "Shoe" : "Schuh",
    "Short" : "Kurz",
    "Should, ought" : "Sollen",
    "Shout (verb)" : "Schreien",
    "Show (verb)" : "Zeigen",
    "Shower (verb)" : "Duschen",
    "Sick" : "Krank",
    "Sing" : "Singen",
    "Sister" : "Schwester",
    "Sit (v)" : "Sitzen",
    "Six" : "Sechs",
    "Sixteen" : "Sechzehn",
    "Sixty" : "Sechzig",
    "Size" : "Größe",
    "Skirt" : "Rock",
    "Sky" : "Himmel",
    "Sleep" : "Schlafen",
    "Slow" : "Langsam",
    "Small/little" : "Klein",
    "Smart" : "Klug",
    "Snail" : "Schnecke",
    "Snows (verb)" : "Schneien",
    "So long/Take care" : "Mach's gut",
    "So, thus, therefore" : "Also",
    "Soccer player" : "Fussballspieler",
    "Sofa" : "Sofa",
    "Some" : "Manche",
    "Someone" : "Jemand",
    "Something" : "Etwas",
    "Sometimes" : "Manchmal",
    "Son" : "Sohn",
    "Sort (verb)" : "Sortieren",
    "Soup" : "Suppe",
    "Spain" : "Spanien",
    "Speak" : "Sprechen",
    "Spider" : "Spinne",
    "Spring" : "Frühling",
    "Stain/mark" : "Fleck",
    "Stairway" : "Treppe",
    "Stand (verb)" : "Stehen",
    "Star" : "Stern",
    "Start (verb)" : "Beginnen",
    "Stay" : "Bleiben",
    "Steal" : "Stehlen",
    "Still" : "Noch",
    "Strawberry" : "Erdbeere",
    "Stressful" : "Stressig",
    "Stroll" : "Spazieren",
    "Strong" : "Stark",
    "Student" : "Schüler",
    "Study" : "Studieren",
    "Stylish" : "Schick",
    "Subway" : "U-Bahnstation",
    "Sugar" : "Zucker",
    "Summer" : "Sommer",
    "Sun" : "Sonne",
    "Sunday" : "Sonntag",
    "Sunscreen" : "Sonnencreme",
    "Surf" : "Surfen",
    "Sweatshirt" : "Sweatshirt",
    "Sweden" : "Schweden",
    "Swedish" : "Schwedisch",
    "Sweet" : "Süß",
    "Swim" : "Schwimmen",
    "Swimming pool" : "Schwimmbad",
    "Swiss" : "Schweizer/in",
    "Switzerland" : "die Schweiz",
    "Syria" : "Syrien",
    "T-shirt" : "T-shirt",
    "Table" : "Tisch",
    "Take" : "Nehmen",
    "Taxi stand" : "Taxistand",
    "Tea" : "Tee",
    "Teacher" : "Lehrer",
    "Team" : "Mannschaft",
    "Television" : "Fernseher",
    "Tell" : "Erzählen",
    "Ten" : "Zehn",
    "Thank you very much" : "Vielen dank",
    "Thanks" : "Danke",
    "Then" : "Dann",
    "There" : "Dort/Da",
    "They are" : "Sie sind",
    "Thief" : "Dieb",
    "Thing" : "Ding",
    "Think" : "Denken",
    "Thirst" : "Durst",
    "Thirteen" : "Dreizehn",
    "Thirty" : "Dreißig",
    "This" : "Diese",
    "Thousand" : "(ein)tausend",
    "Three" : "Drei",
    "Tickets" : "Fahrkarten",
    "Time" : "Zeit",
    "Tired" : "Müde",
    "To punch/kick" : "Stoßen",
    "Today" : "Heute",
    "Together" : "Zusammen",
    "Tomato" : "Tomate",
    "Tomorrow" : "Morgen",
    "Too bad" : "Schade",
    "Tooth" : "Zahn",
    "Train" : "Zug",
    "Train station" : "Bahnhof",
    "Travel" : "Reisen",
    "Tree" : "Baum",
    "Try/Taste" : "Probieren",
    "Turkey" : "Türkei",
    "Turkish" : "Türkisch",
    "Twelve" : "Zwölf",
    "Twenty" : "Zwanzig",
    "Two" : "Zwei",
    "Ugly" : "Hässlich",
    "Umbrella" : "Regenschirm",
    "Uncle" : "Onkel",
    "Understand" : "Verstehen",
    "Unfortunately" : "Leider",
    "University" : "Universität",
    "Until when?" : "Bis wann?",
    "Use (verb)" : "Benutzen",
    "Use, utilize" : "Verwenden",
    "Vacation" : "Urlaub",
    "Vase" : "Vase",
    "Vegetables" : "Gemüse",
    "Very" : "Sehr",
    "Vicinity" : "Nähe",
    "Video game" : "Videospiel",
    "Visit" : "Besuchen",
    "Wait" : "Warten",
    "Waiter" : "Kellner",
    "Walk" : "Laufen",
    "Want" : "Wollen",
    "Warm" : "Warm",
    "Warsaw" : "Warschau",
    "Wash" : "Waschen",
    "Watch" : "Schauen",
    "Water" : "Wasser",
    "We are" : "Wir sind",
    "Weak" : "Schwach",
    "Wear" : "Tragen",
    "Weather" : "Wetter",
    "Week" : "Wöche",
    "Weekend" : "Wochenende",
    "Welcome" : "Willkommen",
    "What is that?" : "Was ist das?",
    "What is your name? (formal)" : "Wie heißen Sie?",
    "When" : "Wann?",
    "Where" : "Wo?",
    "Where do you come from?(formal)?" : "Woher kommen Sie?",
    "Where from" : "Woher?",
    "Where going" : "Wohin?",
    "Where is?" : "Wo ist?",
    "Which" : "Welche?",
    "While" : "Während",
    "White" : "Weiß",
    "Who is that?" : "Wer ist das?",
    "Why" : "Warum?",
    "Wind" : "Wind",
    "Windows" : "Fenster",
    "Windy" : "Windig",
    "Wine" : "Wein",
    "Winter" : "Winter",
    "With" : "Mit",
    "Wonderful" : "Wunderbar",
    "Work (verb)" : "Arbeiten",
    "Write" : "Schreiben",
    "Year" : "Jahr",
    "Yellow" : "Gelb",
    "Yesterday" : "Gestern",
    "You're welcome" : "Gern geschehen",
    "You're welcome (2)" : "Bitte",
    "Young" : "Jung",
    "Zero" : "Null",
    "you are (formal, sing./plural)" : "Sie sind",
    "you are (informal, plural)" : "Ihr seid",
    "you are (informal, singular)" : "du bist",
}

Vocabulary_neu = {

    "Angry (2)" : "Sauer",
    "Rain (verb)" : "Regnen",
    "Possess" : "Besitzen",
    "Maintain/Receive (2)" : "Erhalten",
    "Recognize" : "Erkennen",
    "Describe" : "Beschreiben",
    "Serve" : "Dienen",
    "Follow" : "Folgen",
    "Impress" : "Imponieren",
    "Central America" : "Mittelamerika",
    "South America" : "Südamerika",
    "Great Britain" : "Großbritannien",
    "Ireland" : "Irland",
    "Netherlands" : "Die Niederlande",
    "Portugal" : "Portugal",
    "Romania" : "Rumänien",
    "Slovakia" : "Die Slowakei",
    "Czech Republic" : "Tschechien",
    "Careful" : "Vorsichtig",
    "Quit" : "Kündigen",
    "Burn" : "Brennen",
    "Cry" : "Weinen",
    "Solve" : "Lösen",
    "Be missing, lack" : "Fehlen",
    "Practice (verb)" : "Üben",
    "Chinese" : "Chinesisch",
    "Note (verb)" : "Notieren",
    "Whole/Complete" : "Ganz",
    "Meanwhile/Meantime" : "Mittlerweile",
    "Arrest/Detain" : "Verhaften",
    "Suddenly" : "Plötzlich",
    "Laugh (verb)" : "Lachen",
    "Terrible/Bad" : "Schlimm",
    "Dangerous" : "Gefährlich",
    "Quiet/Still" : "Still",
    "Outside" : "Draußen",
    "Feel (verb)" : "Fühlen",
    "Satisfied/Content" : "Zufrieden",
    "Are you okay?" : "Ist dir was passiert?",
    "Keep/Hold" : "Halten",
    "Firm/Fixed" : "Fest",
    "I don't care" : "Mir ist das egal",
    "Because of/On account of" : "Wegen",
    "Speak/Talk" : "Reden",
    "Annoy/Bother" : "Nerven",
    "All the same" : "Egal",
    "Let/Allow" : "Lassen",
    "Bully/Harass (verb)" : "Mobben",
    "Threaten" : "Bedrohen",
    "Hurt/Wound" : "Verletzen",
    "Fury/Rage" : "Die Wut",
    "Forest/Wood" : "Der Wald",
    "Surprise (verb)" : "Überraschen",
    "Tempo/Pace" : "Das Tempo",
    "Remember/Remind" : "Erinnern",
    "Hug/Embrace" : "Umarmen",

}

Vocabulary_nommen = {

    "A few/a couple of" : "Das Paar,-e",
    "ATM" : "Der Geldautomat,-en",
    "Actor" : "Der Schauspieler,-",
    "Admission ticket" : "Die Eintrittskarte,-n",
    "Adress" : "Die Adresse,-n",
    "Afternoon" : "Der Nachmittag,-e",
    "Age" : "Das Alter,-",
    "Air" : "Die Luft,Lüfte",
    "Airplane" : "Das Flugzeug,-e",
    "Airport" : "Der Flughafen,Flughäfen",
    "Animal" : "Das Tier,-e",
    "Announcement" : "Die Ansage,-n",
    "Answering machine" : "Der Anrufbeantworter,-",
    "Apartment" : "Die Wohnung,-en",
    "Arm" : "Der Arm,-e",
    "Arrival" : "Die Ankunft,Anküfte",
    "Art Museum" : "Die Kunsthalle,-n",
    "Artist" : "Der Künstler,-",
    "Aunt" : "Die Tante,-n",
    "Baby" : "Das Baby,-s",
    "Bag (feminine)" : "Die Tasche,-n",
    "Bag (plastic)" : "Die Tüte,-n",
    "Bakery" : "Die Bäckerei,-en",
    "Ballpoint pen" : "Der Kuli,-s",
    "Banana" : "Die Banane,-n",
    "Basket" : "Der Korb,Körbe",
    "Bathroom" : "Das Badezimmer,-",
    "Bear" : "Der Bär,-en",

    "Beard" : "Der Bart",
    "Beauty" : "Die Schönheit",
    "Bed" : "Das Bett",
    "Bedroom" : "Das Schlafzimmer",
    "Bee" : "Die Biene",
    "Beer" : "Das Bier",
    "Beetle" : "Der Käfer",
    "Beginning" : "Der Anfang",
    "Bicycle" : "Das Fahrrad",
    "Bird" : "Der Vogel",
    "Birthday" : "Der Geburtstag",
    "Blouse" : "Die Bluse",
    "Bookcase" : "Das Bücherregal",
    "Bottle" : "Die Flasche",
    "Bowl" : "Die Schale",
    "Boy" : "Der Junge",
    "Bread" : "Das Brot",
    "Breakfast" : "Das Frühstück",
    "Brightness" : "Die Helligkeit",
    "Brother" : "Der Bruder",
    "Butcher" : "Der Metzger",
    "Button (clothes)" : "Der Knopf",
    "Call" : "Der Anruf",
    "Car" : "Der Wagen",
    "Carpet" : "Der Teppich",
    "Cash register" : "Die Kasse",
    "Cat" : "Die Katze",
    "Cellphone" : "Das Handy",
    "Chair" : "Der Stuhl",
    "Chancellor" : "Der Kanzler",
    "Check" : "Die Rechnung",
    "Cheers" : "Das Prost",
    "Cheese" : "Der Käse",
    "Chess" : "Das Schach",
    "Chicken" : "Das Hähnchen",
    "Child" : "Das Kind",
    "Chocolate" : "Die Schokolade",
    "Cinema" : "Das Kino",
    "City" : "Die Stadt",
    "Class/Course" : "Der Kurs",
    "Clock" : "Die Uhr",
    "Closet" : "Der Schrank",
    "Clothes" : "Die Kleidung",
    "Cloud" : "Die Wolke",
    "Clown" : "Der Clown",
    "Coat" : "Der Mantel",
    "Coffee" : "Der Kaffee",
    "Computer" : "Der Computer",
    "Concert" : "Das Konzert",
    "Corner" : "Die Ecke",
    "Cosmetics" : "Die Kosmetiks",
    "Cost" : "Die Kosten",
    "Couch" : "Die Couch",
    "Cow" : "Die Kuh",
    "Credit card" : "Die Kreditkarte",
    "Cup" : "Die Tasse",
    "Dance (noun)" : "Der Tanz",
    "Danger, Caution" : "Die Achtung",
    "Date" : "Das Date",
    "Daughter" : "Die Tochter",
    "Dentist" : "Der Zahnarzt",
    "Department store" : "Das Kaufhaus",
    "Departure" : "Die Abfahrt",
    "Desk" : "Der Schreibtisch",
    "Dictionary" : "Das Wörterbuch",
    "Dinner" : "Das Abendessen",
    "Doctor" : "Der Arzt",
    "Dog" : "Der Hund",
    "Door" : "Die Tür",
    "Dress" : "Das Kleid",
    "Duck" : "Die Ente",
    "Earth" : "Die Erde",
    "Egg" : "Das Ei",
    "Elephant" : "Der Elefant",
    "Elevator" : "Der Aufzug",
    "Exam" : "Das Examen",
    "Fall/Autumn (2)" : "Der Herbst",
    "Family" : "Die Familie",
    "Father" : "Der Vater",
    "Fear" : "Die Angst",
    "Feather" : "Die Feder",
    "Fire" : "Das Feuer",
    "Fish" : "Der Fisch",
    "Floor" : "Der Boden",
    "Flower" : "Die Blume",
    "Food" : "Das Essen",
    "Food/Dish" : "Die Speise",
    "Football game" : "Das Fußballspiel",
    "Foreigner" : "Der Ausländer",
    "French fries" : "Die Pommes",
    "Friend" : "Der Freund",
    "Friend/Girlfriend" : "Die Freundin",
    "Fruit" : "Das Obst",
    "Fun" : "Der Spaß",
    "Furniture" : "Das Möbel",
    "Game" : "Das Spiel",
    "Gender" : "Das Geschlecht",
    "Gift" : "Das Geschenk",
    "Girl" : "Das Mädchen",
    "Glass" : "Das Glas",
    "Government" : "Die Regierung",
    "Grandfather" : "Der Großvater",
    "Grandmother" : "Die Großmutter",
    "Greeting" : "Der Gruß",
    "Guest" : "Der Gest",
    "Guitar" : "Die Gitarre",
    "Hair" : "Das Haar",
    "Hand" : "Die Hand",
    "Hat" : "Der Hut",
    "Hell" : "Die Hölle",
    "Help (noun)" : "Die Hilfe",
    "Hike (noun)" : "Die Wanderung",
    "Horse" : "Das Pferd",
    "Hour" : "Die Stunde",
    "House" : "Das Haus",
    "Hunger" : "Der Hunger",
    "Husband" : "Der Ehemann",
    "Ice-cream" : "Das Eis",
    "Idea" : "Die Idee",
    "Idea (2)" : "Die Ahnung",
    "Insect" : "Das Insekt",
    "Instruction, teaching" : "Der Unterricht",
    "Invitation" : "Die Einladung",
    "Jacket" : "Die Jacke",
    "Jewelry" : "Der Schmuck",
    "Job interview" : "Das Jobinterview",
    "Key" : "Der Schlüssel",
    "King" : "Der König",
    "Kitchen" : "Die Küche",
    "Lady" : "Die Dame",
    "Lake" : "Der See",
    "Lamp" : "Die Lampe",
    "Language" : "Die Sprache",
    "Lawyer" : "Der Anwalt",
    "Lesson" : "Die Lektion",
    "Letter" : "Der Brief",
    "Letter (of a word)" : "Der Buchstabe",
    "Library" : "Die Bibliothek",
    "Magazine" : "Die Zeitschrift",
    "Man" : "Der Mann",
    "Market" : "Der Markt",
    "Meat" : "Das Fleisch",
    "Mechanic" : "Der Mechaniker,-",
    "Menu" : "Die Speisekarte,-n",
    "Mineral water" : "Das Mineralwasser,-",
    "Minute" : "Die Minute",
    "Mirror" : "Der Spiegel,-",
    "Miss" : "Die Frau,-en",
    "Monday" : "Der Montag,-e",
    "Money" : "Das Geld,-er",
    "Moon" : "Der Mond,-e",
    "Mother" : "Die Mutter,Mütter",
    "Mountain" : "Der Berg,-e",
    "Mouse" : "Die Maus,Mäuse",
    "Movie" : "Der Film,-e",
    "Nature" : "Die Natur,-en",
    "Newspaper" : "Die Zeitung,-en",
    "Noodle/pasta" : "Die Nudel,-n",
    "Notebook" : "Das Heft,-e",
    "Number" : "Die Zahl",
    "Nurse" : "Die Krankenschwester,-n",
    "Offer" : "Das Angebot",
    "Oil" : "Das Öl,-e",
    "Orange (fruit)" : "Die Orange,-n",
    "Oven" : "Der Ofen,Öfen",
    "Owl" : "Die Eule,-n",
    "Pants" : "Die Hose,-n",
    "Parent" : "Das Elter,-n",
    "Park" : "Der Park,-s",
    "Parrot" : "Der Papagei,-en",
    "Participant (masculine)" : "Der Teilnehmer",
    "Party" : "Die Party,-s",
    "Passport" : "Der Pass,Pässe",
    "Path" : "Der Weg",
    "Pen" : "Der Stift,-e",
    "Pencil" : "Der Bleistift,-e",
    "People" : "Die Leute",
    "Pet" : "Das Haustier,-e",
    "Pharmacy" : "Die Apotheke,-n",
    "Piano" : "Das Klavier,-e",
    "Picture" : "Das Bild,-er",
    "Pig" : "Das Schwein,-e",
    "Pillow" : "Das Kissen",
    "Plant" : "Die Pflanze",
    "Pronunciation" : "Die Aussprache",
    "Queen" : "Die Königin",
    "Registration, enrollment" : "Die Anmeldung",
    "Reservation" : "Die Reservierung",
    "Result" : "Das Ergebnis",
    "Sea/Ocean" : "Die See",
    "Seat" : "Der Sitz",
    "Sender" : "Der Absender",
    "Sibling" : "Das Geschwister",
    "Story" : "Die Geschichte",
    "Street number" : "Die Hausnummer",
    "Suit jacket" : "Das Sakko",
    "Toilet" : "Die Toilette",
    "Track (train)" : "Das Gleis",
    "Travel center" : "Das Reisezentrum",
    "Tuesday" : "Der Dienstag",
    "Vegetarian" : "Der Vegetarier",
    "Violine" : "Die Geige",
    "Wall" : "Die Wand",
    "Wednesday" : "Der Mittwoch",




}

Vocabulary_neue_nommen = {

    #alte nommen


    #neue nommen! 
    "Beach" : "Der Strand,Strände",
    "Suitcase/Bag" : "Der Koffer,-",
    "South" : "Der Süden",
    "North" : "Der Norden",
    "West" : "Der Westen",
    "East" : "Der Osten",
    "Radio" : "Das Radio,-s",
    "Accident" : "Der Unfall, Unfälle",
    "Antartica" : "Die Antarktis,-",
    "Earth" : "Die Erde, -n",
    "Continent" : "Der Erdteil, -e",
    "Surfboard" : "Das Surfbrett, -er",
    "Desire/Lust" : "Die Lust",
    "Danger/Risk" : "Die Gefahr",
    "Mood" : "Die Laune",
    "Conclusion/End" : "Der Schluss",
    "Exhibition/Display" : "Die Ausstellung",
    "Coward/Chicken" : "Der Feigling",
    "Answer/Communication" : "Der Bescheid",
    "Nonsense" : "Der Schmarren",
    "Peace" : "Der Frieden",
    "Pain/Ache" : "Das Weh",
    "Error/Fault" : "Der Fehler",
    "Song" : "Das Lied",
    "Devil/Demon" : "Der Taufel",
    "Exam (2)" : "Die Prüfung",
    







}

Vocabulary_trennbare_verben = {

    "Agree (with)" : "Zustimmen",
    "Approach/Collide" : "Anfahren",
    "Arrive" : "Ankommen",
    "Ascribe/Attribute" : "Zuschreiben",
    "Begin (verb)" : "Anfangen",
    "Cancel/Call of" : "Absagen",
    "Carry out/Execute" : "Ausführen",
    "Cease/End" : "Aufhören",
    "Change clothes" : "Umziehen",
    "Choose" : "Auswählen",
    "Choose/Select" : "Aussuchen",
    "Clean up/ tidy up" : "Aufräumen",  
    "Clean/ tidy up (2)" : "Saubermachen",     
    "Close (verb)" : "Zumachen",
    "Concern, tackle, approach" : "Angehen", 
    "Come back" : "Wiederkommen",
    "Complete/Finish" : "Fertigmachen",
    "Depart" : "Abfahren",
    "Depart/Leave" : "Weggehen",
    "Drive in/Enter" : "Reinfahren",
    "Excite" : "Aufregen",
    "Enter/Input" : "Eingeben",
    "Fall asleep" : "Einschlafen",
    "Get on (transportation)" : "Einsteigen",
    "Get there/Manage" : "Hinkommen",        
    "Go along" : "Mitgehen",
    "Go in/Enter" : "Reingehen",
    "Hand over, deliver" : "Abgeben",        
    "Introduce" : "Vorstellen",
    "Invite" : "Einladen",
    "Keep hold of" : "Festhalten",
    "Lean against" : "Anlehnen",
    "Leave" : "Losgehen",
    "Look around" : "Umschauen",
    "Look at, watch" : "Ansehen",
    "Look like" : "Aussehen",
    "Make a date" : "Verabreden",
    "Move" : "Umziehen",
    "Offer/ Propose" : "Anbieten",
    "Open (verb)" : "Aufmachen",
    "Participate" : "Mitmachen",
    "Pay attention/Watch out" : "Aufpassen",
    "Pick up/ Collect" : "Abholen",
    "Prepare" : "Vorbereiten",
    "Pronounce" : "Aussprechen",
    "Put down/assign" : "Abstellen",
    "Register/Enroll" : "Anmelden",
    "Relax" : "Ausruhen",
    "Spend" : "Ausgeben",
    "Stand/get up" : "Aufstehen",
    "Switch on/Intervene" : "Einschalten",
    "Take along" : "Mitnehmen",
    "Take away" : "Wegnehmen",
    "Telephone (verb)" : "Anrufen",
    "Throw away" : "Wegwerfen",
    "Tick, cross" : "Ankreuzen",
    "Transfer (to other transportation)" : "Umsteigen",
    "Turn off" : "Ausmachen",
    "Turn on" : "Anmachen",
    "Wake up" : "Aufwachen",
    "Walking" : "Spazierengehen",
    "Write down" : "Aufschreiben",


}

Vocabulary_Kapitel_10 = {

     #Sequenz 1: Kontakte pflegen
    "Average" : "Der Durchschnitt",
    "Hour" : "Die Stunde,-n",
    "Web" : "Das Netz",
    "Use (verb)" : "Nutzen",
    "Surf (internet)" : "Surfen",
    "Smartphone" : "Das Smartphone,-s",
    "Communication" : "Die Kommunikation",
    "Information" : "Die Information,-en",
    "So, thus" : "Also",
    "Chat (verb)" : "Chatten",
    "Telephone (verb)" : "Telefonieren",
    "For example" : "Zum Beispiel",
    "Search engine" : "Die Suchmaschine,-n",
    "Simply" : "Einfach",
    "Blog" : "Der Blog,-s",
    "Video" : "Das Video,-s",
    "Social" : "Sozial",
    "Network" : "Das Netzwerk,-e",
    "Particularly, especially" : "Besonders",
    "Young" : "Jung",
    "Second (about time)" : "Die Sekunde,-n",
    "Since" : "Seit",
    "Call (noun)" : "Der Anruf,-e",
    "Connection" : "Die Verbindung,-en",
    "Finished" : "Beendet",
    "Begin" : "Beginnen",
    "Duration" : "Die Dauer",
    "Telephone" : "Das Telefon,-e",
    "Login" : "Der Login,-s",
    "Register" : "Registrieren",
    "Registration" : "Die Registrierung,-en",
    "Possible" : "Möglich",
    "Pasta" : "Die Pasta",
    "Recipe" : "Das Rezept,-e",
    "Fresh" : "Frisch",
    "Nothing" : "Nichts",
    "Wine cellar" : "Der Weinkeller",
    "Reader" : "Der Leser",
    "Zucchini" : "Der Zucchini,-s",
    "Ingredient" : "Die Zutat,-en",
    "Statement" : "Die Aussage,-n",
    "Tip" : "Der Tipp,-s",
    "Cooking pasta (noun)" : "Das Pastakochen",
    "Party (2)" : "Das Fest,-e",
    "Chatting" : "Das Chatten",
    "Path" : "Der Weg,-e",
    "E-mail" : "Die E-mail,-s",
    "Programmer (masc/fem)" : "Der Programmierer/in",
    "Send (2)" : "Verschicken",
    "Making phone calls" : "Das Telefonieren",
    "Following/subsequent" : "Folgend(e)",
    "Program" : "Das Programm,-e",
    "App" : "Die App,-s",
    
    #Sequenz 2: Freunde und Nachbarn
    "Oh well" : "Na ja",
    "Manage, achieve, accomplish" : "Schaffen",
    "Help (noun)" : "Die Hilfe,-n",
    "Offer (verb)" : "An|bieten",
    "Refuse/decline" : "Ab|lehnen",
    "Carry/take" : "Tragen",
    "New Year's Eve party" : "Die Silvesterparty,-s",
    "Sparkling wine" : "Der Sekt",
    "Enough" : "Genug",
    "Firework" : "Das Feuerwerk,-e",
    "Dialogue" : "Der Dialog,-e",
    "Know each other" : "Sich kennen",
    "Happy new year" : "Gutes neues Jahr",
    "New year's eve" : "Das Silvester",
    "Happy new year (2)" : "Frohes neues Jahr",
    "Birthday cake" : "Der Geburtstagskuchen",
    "As far as/So far" : "Soweit",
    "Whether/if" : "Ob",
    "Marry" : "Heiraten",
    "Wedding" : "Die Trauung,-en",
    "Take place" : "Statt|finden",
    "Wedding (2)" : "Die Hochzeit,-en",
    "The Christmas dinner" : "Das Weihnachtessen",
    "Forget" : "Vergessen",
    "Congratulations" : "Glückwunsch,-e",
    "Christmas" : "Das Weihnachten",
    "Merry Christmas" : "Frohe Weihnachten",

    #Sequenz 3: Treffpunkte
    "Swimming pool" : "Das Schwimmbad,Schwimmbäder",
    "Playing guitar" : "Gitarre spielen",
    "Come back" : "Wieder|kommen",
    "Funny" : "Lustig",
    "Recommend" : "Empfehlen",
    "International" : "International",
    "Product" : "Das Produkt,-e",
    "Positive" : "Positiv",
    "Negative" : "Negativ",
    "Enthusiastic" : "Begeistert",
    "Summer night" : "Die Sommernacht,Sommernächte",
    "Cooking (noun)" : "Das Kochen",
    "Theater workshop" : "Der Theater-Workshop,-s",
    "Music arena" : "Die Musik-Arena",
    "Later" : "Später",
    "Beginning of a word" : "Der Wortanfang,Wortanfänge",
    "Ending of a word" : "Das Wortende,-n",
    "Art" : "Die Kunst,Künste",
    "Syllable" : "Die Silbe,-n",
    "Pronounce" : "Aussprechen",

    # 15 März
    "Above" : "Über",
    "Answer (verb, direct person)" : "Beantworten",
    "Certain, safe, sure" : "Sicher",
    "Colleague (masc)" : "Der Kollege,-n",
    "Congratulate" : "Gratulieren",
    "Divorced" : "Geschieden",
    "Download (verb)" : "herunter|laden",
    "File" : "Die Datei",
    "Folder" : "Der Ordner,-s",
    "Married" : "Verheiratet",
    "Origin" : "Die Herkunft",
    "Other (adj)" : "Andere",
    "Person" : "Die Person,-en",
    "Place of residence" : "Der Wohnort",
    "Post (verb)" : "Posten",
    "Send" : "Senden",
    "Send (for peopl/things)" : "Verschicken",
    "Shopping (verb)" : "Ein|kaufen",
    "Single/Unmarried" : "Ledig",
    "Thing (2)" : "Die Sache,-n",
    "Upload (verb)" : "Hoch|laden",
    "Use (noun)" : "Die Nutzung",
    "User" : "Der User",
    "User (2)" : "Der Nutzer",

    # 22 März
    "Contribution" : "Der Beitrag",
    "Pedestrian (male)" : "Der Fußgänger",
    "Task" : "Die Aufgabe",
    "Discover" : "Entdecken",
    "Little/few" : "Wenig",
    "Exercise (noun)" : "Die Übung",
    "Correct (2)" : "Korrekt",
    "Motivation" : "Die Motivation",
    "Success" : "Der Erfolg",
    "Interview" : "Das Interview",
    "Argentina" : "Argentinien",
    "Map" : "Der Stadtplan",
    "Castle (Residency)" : "Das Schloss",
    "Castle (Military)" : "Der Burg",
    "Church" : "Die Kirche",
    "Bridge" : "Die Brücke",
    "Stroller" : "Der Kinderwagen",
    "At least" : "Mindestens",
    "Mostly/largely" : "Meistens",
    "Wish (verb)" : "Wünschen",
    "Terrible" : "Schrecklich",
    "Difficult" : "Schwierig",
    "Enthusiastic" : "Begeistert",
    
}
    
Vocabulary_Kapitel_11 = {

    #Sequenz 1: Besuch in Heidelberg
    "City tour" : "Die Stadtrundfahrt,-en",
    "Castle" : "Das Schloss,Schlösser",
    "City map" : "Der Stadtplan,Stadtpläne",
    "Ask/Request" : "bitten",
    "React" : "Reagieren",
    "Departure time" : "Die Abfahrtszeit,-en",
    "May/Can/Be allowed to" : "Dürfen",
    "University museum" : "Das Universitätmuseum,Universitätmuseen",
    "Around the corner" : "Um die Ecke",
    "Something" : "Was(etwas)",
    "Us" : "Uns(wir)",
    "Father" : "Der Vater,Väter",
    "Give/Present" : "Schenken",
    "Him" : "Ihm",
    "Stroller" : "Der Kinderwagen,Kinderwägen",
    "Heavy" : "Schwer",
    "Thank (verb)" : "Danken",
    "Plan/Map" : "Der Plan,Pläne",
    "Immediately" : "Sofort",
    "Admission price" : "Der Eintrittspreis,-e",
    "Including/Inclusive" : "Inklusive",
    "Adult" : "Der/Die Erwachsene,-n",
    "Person with discount" : "Der/Die Ermäßigte,-n",
    "Guidance/Lead" : "Die Führung,-en",
    "Group" : "Die Gruppe,-n",
    "Student" : "Der Schüler,-",
    "Student feminine" : "Die Schülerin,-nen",
    "Senior citizen" : "Der Senior,-en",
    "Korean" : "Koreanisch",
    "Japanese" : "Japanisch",
    "Bank" : "Die Bank,-en",
    "Money" : "Das Geld",
    "ATM" : "Der Geldautomat",
    "Mail post" : "Die Post",
    "Museum shop" : "Der Museumsshop",
    "Postcard" : "Die Postkarte,-n",
    "Souvenir" : "Das Souvenir,-s",
    "Brochure" : "Der Prospekt,-e",
    "City centre" : "Das Stadtzentrum",
    "You're welcome" : "Bitte sehr",
    "Abroad/Foreign countries" : "Das Ausland",
    "Norway" : "Norwegen",
    "Canada" : "Kanada",
    "Send (3)" : "Schicken",
    "Topic" : "Das Thema,Themen",
    "Shopping (noun)" : "Das Einkaufen",
    "Travelling (noun)" : "Das Reisen",
    "Train ticket" : "Das Zugticket,-s",
    "Bus timetable" : "Der Busfahrplan,Busfahrpläne",

    #Sequenz 2: Ich bin leider zu spät
    "Time indication" : "Die Zeitangabe,-n",
    "Delay" : "Die Verspätung,-en",
    "Hospital" : "Das Hospital,-e",
    "Need (verb)" : "Brauchen",
    "Punctual" : "Pünktlich",
    "Engineer (male)" : "Der Ingenieur,-e",
    "Engineer (female)" : "Die ingenieurin,-nen",
    "Photographer (male)" : "Der Fotograf,-en",
    "Photographer (female)" : "Die Fotografin,-nen",
    "Photo studio" : "Das Fotostudio,-s",
    "Center" : "Das Zentrum,Zentren",
    "Normally" : "Normalerweise",
    "Sometimes" : "Manchmal",
    "Traffic jam" : "Der Stau,-s",
    "Chemistry" : "Die Chemie",
    "Tram" : "Die Straßenbahn,-en",
    "On foot" : "zu Fuß (gehen)",
    "Stand" : "Stehen",
    "Something (2)" : "Etwas",
    "Mark/Time" : "Das Mal",
    "Breakdown/Malfunction" : "Die Panne,-n",
    "Portugal" : "Portugal",
    "Punctuality/Accuracy" : "Die Pünktlichkeit",
    "Official/Officially" : "Offiziell",
    "One/People" : "Man",
    "Funny/Strange" : "Komisch",
    "Unpunctual" : "Unpünktlich",
    "Homeland, Native country" : "Das Heimatland,Heimatländer",

    #Sequenz 3: Wie geht das?
    "Print" : "Drucken",
    "Scanner" : "Der Scanner",
    "Scan" : "Scannen",
    "Copy (verb)" : "Kopieren",
    "Copy (noun)" : "Die Kopie,-n",
    "Download (noun)" : "Der Download,-s",
    "Download (verb)" : "Downloaden",
    "Download (verb,2)" : "Herunter|laden",
    "Button" : "Der Button,-s",
    "Press" : "Drücken",
    "Click (verb)" : "Klicken",
    "Paper" : "Das Papier,-e",
    "Explain" : "Erklären",
    "Copy (verb noun)" : "Das Kopieren",
    "Choose" : "Wählen",
    "Color copy" : "Die Farbkopie,-n",
    "Number/Quantity" : "Die Anzahl,-en",
    "Enter/Input" : "Ein|geben",
    "Album" : "Das Album,Alben",

    #Übungen
    "Office" : "Das Büro",
    "Bike/Wheel" : "Das Rad",
    "Appointment" : "Der Termin",
    "Polite" : "Höflich",
    "Boss" : "Der Chef",
    "Color" : "Die Farbe",
    "ID" : "Der Ausweis",
    "Copier" : "Der Kopierer",
    "Click (noun)" : "Der Klick",
    "Click (verb)" : "An|klicken",
    "Press a button" : "Einen Button drücken",
    "How does that work?" : "Wie geht das denn?",
    "Instruction" : "Die Anleitung",
    "Create" : "Erstellen",
    "Admission" : "Der Eintritt",
    "Practice/Excercise (verb)" : "Üben",

    #29 März
    "Cheerful/lively" : "Munter",
    "Motivated" : "Motiviert",
    "Satisfied/content" : "Zufrieden",
    "Cough" : "Der Husten",
    "Fever" : "Das Fieber",
    "Have breafkast (verb)" : "Frühstücken",
    "Early/initial" : "Früh",
    "Touristic" : "Touristische",
    "Attraction" : "Die Attraktion,-en",
    "Vineyard" : "Der Weinberg",
    "Tower" : "Der Turm",
    "Holy Spirit Church" : "Die Heiliggeistkirche",
    "View (verb)" : "Besichtigen",
    "Excursion" : "Der Ausflug",
    "Bicycle tour" : "Die Fahrradtour",
    "Pub/Bar" : "Die Kneipe",
    "Glasses" : "Die Brille",

}

Vocabulary_Kapitel_12 = {
 
    #Sequenz 1: Das Praktikum
    "Agency/Bureau" : "Die Agentur,-en",
    "Commitment/Promise/Acceptance" : "Die Zusage",
    "Internship" : "Das Praktikum",
    "Dear Mrs" : "Sehr geehrte Frau",
    "Dear Mr" : "Sehr geehrter Herr",
    "Application/Job application" : "Die Bewerbung,-en",
    "Telephone conversation/Phone call" : "Das Telefongespräch,-e",
    "Workday" : "Der Arbeitstag,-e",
    "Greet/Welcome (verb)" : "Begrüßen",
    "Secretariat" : "Das Sekretariat,-e",
    "Personnel Agency" : "Die Personalagentur,-en",
    "Inform (verb)" : "Informieren",
    "Lead/Conduct" : "Leiten",
    "Intern (male)" : "Der Praktikant,-en",
    "Intern (female)" : "Die Praktikantin,-nen",
    "Marketing" : "Das Marketing",
    "Be here" : "Da sein",
    "Oh" : "Oh weh",
    "Chaos" : "Das Chaos",
    "Eye" : "Das Auge,-n",
    "Only" : "Nur",
    "Applicant/Candidat (male)" : "Der Bewerber",
    "Applicant/Candidat (female)" : "Die Bewerberin,-nen",
    "Fast (2)" : "Fix",
    "Otherwise/Else" : "Sonst",
    "Angry (2)" : "Sauer",
    "Wall" : "Die Wand",
    "Desk" : "Der Schreibtisch",
    "Business card" : "Die Visitenkarte",
    "Plant" : "Die Pflanze,-n",
    "Poster" : "Das Plakat",
    "Calendar" : "Der Kalendar",
    "Room/Space" : "Der Raum,Räume",
    "Start (Verb,2)" : "Starten",
    "Print" : "Aus|drucken",
    "Discussion/Meeting" : "Die Besprechung",
    "Mean, to mean (verb)" : "Heißen",
    "Mean (verb,2)" : "Bedeuten",

    #Sequenz 2: Neuer Job, neue Stadt
    "To" : "An",
    "Inbox/Incoming mail" : "Der Posteingang,Posteingänge",
    "Sending (noun)" : "Das Senden",
    "Rubbish bin" : "Der Papierkorb,Papierkörbe",
    "Job" : "Der Job,-s",
    "Whole/Complete" : "Ganz",
    "Different/Distinct" : "Anders",
    "When/Than/As" : "Als",
    "Studies/Study" : "Das Studium,Studien",
    "Canteen/Cafeteria" : "Die Kantine,-n",
    "Coffee machine" : "Die Kaffeemaschine,-n",
    "Speak/talk" : "Reden",
    "Room number" : "Die Zimmernummer,-n",
    "At midday" : "Zu Mittag",
    "Ground meat" : "Das Hackfleisch",
    "First/At first/Firstly" : "Zuerst",
    "Concept/Idea" : "Das Konzept",
    "Website" : "Die Internetseite,-n",
    "Content" : "Der Inhalt",
    "Side/Page" : "Die seite,-n",
    "Schedule/Time plan" : "Der Zeitplan,Zeitpläne",
    "Agenda" : "Die Agenda,Agenden",
    "Discussion/Argument" : "Die Diskussion,-en",

    #Übungen
    "Promise/agree (verb)" : "Zu|sagen",
    "Ballpoint pen" : "Der Kugelschreiber",
    "Sound (verb)" : "Klingen",
    "Sound (noun)" : "Der Klang",
    "Great/Awesome" : "Klasse",
    "First/At first" : "Zuerst",
    "Together (2)" : "Gemeinsam",
    "Content/Substance" : "Der Inhalt",
    "Schedule (2)" : "Der Zeitplan",
    "Conversation/Dialogue" : "Das Gespräch",
    "Choose (2)" : "Aus|wählen",
    "Clean (2)" : "Putzen",
    "Enjoy" : "Genießen",
    "Folder (2)" : "Die Mappe",
    "Dishes" : "Das Geschirr",
    "Wash (toilette,dishes, etc.)" : "Spülen",
    "Consider/Observe" : "Beachten",
    "Conversation" : "Das Gespräch",
    "Customer" : "Der Kunde/in",
    "Polite" : "Höflich",
    "Insert/Stick" : "Stecken",
    "Absolutely" : "Unbedingt",

    #05 April
    "Screen" : "Der Bildschirm",
    "Ballpoint pen" : "Der Kugelschreiber",
    "Leaf/Sheet" : "Das Blatt",
    "Glasses" : "Die Brille",
    "Mouse" : "Die Maus",
    "Keyboard" : "Die Tastatur",
    "Probably" : "Wohl",
    "Describe" : "Be|schreiben",
    "Box (noun)" : "Die Kiste",
    "Miss (verb)" : "Verpassen",

    #12 April
    "Clean/Tidy up" : "Sauber|machen",
    "Exam" : "Die Prüfung,-en",
    "Bake" : "Backen",
    "Stove" : "Der Herd",
    "Cake" : "Der Kuchen",
    "Kitchen" : "Die Küche",
    "Hard" : "Hart",
    "Number (verb)" : "Nummerieren",
    "Take out" : "Ausführen",
    "Food (for animals)" : "Das Futter",
    "Previous" : "Vorherig",
    "Prohibition/Ban" : "Das Verbot",
    "Permission/Authorization" : "Die Erlaubnis",
    "Cruise ship" : "Das Kreuzfahrtschiff",
    "Box (verb)" : "Boxen",
    "Ping-pong" : "Das Tischtennis",
    "Necklace" : "Die Kette",
    "Smoke (verb)" : "Rauchen",
    "Put down/Assign" : "Ab|stellen",
    "Parcel/Plot" : "Das Grundstück",
    "Surfboard" : "Das Surfbrett",
    "Skate (verb)" : "Skaten",
    "Announce by poster/Put up posters" : "Plakatieren",
    "Shop/Store" : "Der Laden",
    "Business/Enterprise" : "Das Geschäft",
    "Count (verb)" : "Zählen",

}

Vocabulary_Kapitel_13 = {

    #Übungen
    "Grandson" : "Der Enkel",
    "Granddaughter" : "Die Enkelin",
    "Grandchild" : "Das Enkelkind",
    "Separate" : "Trennen",
    "Mother (2)" : "Die Mama",
    "Father (2)" : "Der Papa",
    "Family tree" : "Der Stammbaum",
    "Excellent/Super" : "Prima",
    "Village/Town" : "Das Dorf",
    "Experience (2)" : "Erfahren",
    "Washing machine/Clothes washer" : "Die Waschmaschine",
    "Load the dishwasher" : "Die Spülmaschine einräumen",
    "Unload the dishwasher" : "Die Spülmaschine ausräumen",
    "Turn on the washing machine" : "Die Waschmaschine einschalten",
    "Take out the trash" : "den Müll rausbringen",
    "Hang up the laundry" : "Die Wäsche aufhängen",
    "Wash the dishes" : "Das Geschirr spülen",
    "Clean the windows" : "Die Fenster putzen",
    "Cook/Boil (verb)" : "Kochen",
    "Lay the table" : "Den Tisch decken",
    "Do Homework" : "Machen Hausaufgaben",
    "Note/Memo (noun)" : "Die Notiz",
    "Finally/At last" : "Endlich",
    "Report (noun)" : "Der Bericht",
    "Backpack" : "Der Rucksack",
    "Reason/Bottom" : "Der Grund",
    "Married couple" : "Das Ehepaar",
    "Additionally" : "Dazu",
    "Garden" : "Der Garten",
    "Be glad/Rejoice" : "Freuen",
    "Genuine/Real" : "Echt",
    "Consider/Observe" : "Beachten",

}

Vocabulary_Kapitel_14 = {

    #Übungen
    "Certain/Definite" : "Bestimmt",
    "Earn" : "Verdienen",
    "Open/Inaugurate" : "Eröffnen",
    "Ship" : "Das Schiff",
    "Move/Shift" : "Bewegen",
    "Fall/Topple" : "Stürzen",
    "On the way/On the road" : "Unterwegs",
    "Movement/Motion" : "Die Bewegung",
    "Spell" : "Buchstabieren",


}

Vocabulary_Kapitel_15 = {

    "Win/Gain" : "Gewinnen",

}

from word import Word

Vocabulary_Nicos_Weg_A2_0 = {

    "Sprichst du Deutsch?": [
        Word("Pronounciation", "die Aussprache", example="Deine Aussprache wird immer besser."),
        Word("Definitely, certainly", "bestimmt", example="Das ist bestimmt eine gute Idee."),
        Word("That isn't enough", "das reicht nicht", example="Ein Wort pro Tag lernen, das reicht nicht."),
        Word("Dialect", "der Dialekt,-e", example="In Bayern spricht man einen starken Dialekt."),
        Word("I am interested (in)", "Es interessiert mich", example="Es interessiert mich, wie andere Sprachen funktionieren."),
        Word("Grammar", "die Grammatik", example="Die deutsche Grammatik ist am Anfang schwierig."),
        Word("Greeting", "der Gruß,Grüße", example="Zum Abschied gab es einen herzlichen Gruß."),
        Word("Best regards", "Mit freundlichen Grüßen", example="Mit freundlichen Grüßen, Anna Müller."),
        Word("I would like to know", "Ich möchte gerne wissen", example="Ich möchte gerne wissen, wann der Kurs beginnt."),
        Word("King", "der König,-e", example="Der König lebte in einem großen Schloss."),
        Word("Queen", "die Königin,-nen", example="Die Königin besuchte die Stadt letzte Woche."),
        Word("To take a course", "einen Kurs besuchen", example="Ich möchte einen Deutschkurs besuchen."),
        Word("To have a look, to check, to look up something", "etwas nach|sehen", example="Ich muss noch die Uhrzeit nachsehen."),
        Word("To manage something", "etwas schaffen", example="Ich glaube, du schaffst die Prüfung."),
        Word("Ship", "das Schiff,-e", example="Das Schiff fährt heute Abend ab."),
        Word("Self, oneself", "selbst", example="Das habe ich selbst gekocht."),
        Word("Worry, concern", "die Sorge,-n", example="Mach dir keine Sorgen um mich."),
        Word("To correct, to improve", "etwas verbessern", example="Kannst du meinen Text verbessern?"),
        Word("To agree on something, to arrange something", "etwas vereinbaren", example="Wir haben einen Termin vereinbart."),
        Word("What about ...?, What's up with ...?", "was ist mit ...?", example="Was ist mit deinem Bruder, kommt er auch?"),
        Word("Funny", "witzig", example="Der Film war wirklich witzig."),
    ],

    "Pläne machen": [
        Word("To be afraid", "angst haben", example="Ich habe Angst vor der Prüfung."),
        Word("Work permit", "die Arbeitserlaubnis,-se", example="Ohne Arbeitserlaubnis darf er hier nicht arbeiten."),
        Word("No way, on no account", "auf keinen Fall", example="Das darfst du auf keinen Fall vergessen."),
        Word("Biology", "die Biologie", example="Sie studiert Biologie an der Universität."),
        Word("Success", "der Erfolg,-e", example="Der Erfolg des Projekts hat alle überrascht."),
        Word("Successful", "erfolgreich", example="Sie hat die Prüfung erfolgreich bestanden."),
        Word("To take an exam", "Examen machen", example="Nächstes Jahr möchte ich mein Examen machen."),
        Word("Company", "die Firma,Firmen", example="Er arbeitet bei einer großen Firma."),
        Word("Law", "das Gesetz,-e", example="Das neue Gesetz tritt im Januar in Kraft."),
        Word("Integration", "die Integration", example="Sprachkurse helfen bei der Integration."),
        Word("Intensive course", "der Intensivkurs,-e", example="Der Intensivkurs dauert nur vier Wochen."),
        Word("Law (studying)", "Jura", example="Mein Bruder studiert Jura in München."),
        Word("Opinion", "die Meinung,-en", example="Was ist deine Meinung dazu?"),
        Word("Migrant (male)", "der Migrant,-en", example="Der Migrant lebt seit drei Jahren in Deutschland."),
        Word("Migrant (female)", "die Migrantin,-nen", example="Die Migrantin hat schnell Deutsch gelernt."),
        Word("Even better", "noch besser", example="Mit etwas Übung wird es noch besser."),
        Word("Internship, practical training", "das Praktikum,Praktika", example="Ich mache im Sommer ein Praktikum."),
        Word("Process, procedure", "der Prozess,-e", example="Der Prozess der Anmeldung dauert nicht lange."),
        Word("Studies", "das Studium,Studien", example="Nach dem Studium möchte ich reisen."),
        Word("Goal, target", "das Ziel,-e", example="Mein Ziel ist es, fließend Deutsch zu sprechen."),
        Word("Plans for the future", "der Zukunftsplan,Zukunftspläne", example="Hast du schon konkrete Zukunftspläne?"),
        Word("Future", "die Zukunft,Zukünfte", example="Wie stellst du dir deine Zukunft vor?"),
    ],

    "Angekommen": [
        Word("Beginning", "der Anfang,Anfänge", example="Der Anfang war schwer, aber jetzt läuft es gut."),
        Word("Telephone Call", "der Anruf,-e", example="Ich habe einen Anruf von meiner Mutter bekommen."),
        Word("To have/take a look at something", "sich etwas an|sehen", example="Wir sollten uns die Wohnung ansehen."),
        Word("To look after something/someone", "auf etwas/jemanden auf|passen", example="Kannst du auf meinen Hund aufpassen?"),
        Word("Au-pair (male)", "der Au-Pair-Junge,-n", example="Der Au-Pair-Junge kümmert sich um die Kinder."),
        Word("Au-pair (female)", "das Au-Pair-Mädchen,-", example="Das Au-Pair-Mädchen wohnt bei einer Familie in Berlin."),
        Word("That", "dass", example="Ich hoffe, dass du morgen Zeit hast."),
        Word("Foreign, Strange, Unfamiliar", "fremd", example="Am Anfang fühlte sich alles fremd an."),
        Word("At most, Highest", "höchstens", example="Der Weg dauert höchstens zehn Minuten."),
        Word("Information", "die Information,-en", example="Ich brauche noch ein paar Informationen."),
        Word("Including", "inklusive", example="Die Miete ist inklusive Nebenkosten."),
        Word("At least, Minimum", "mindestens", example="Du solltest mindestens acht Stunden schlafen."),
        Word("To pack something", "etwas packen", example="Ich muss noch meinen Koffer packen."),
        Word("Situation", "die Situation,-en", example="Die Situation war ziemlich kompliziert."),
        Word("Allowance, Pocket money", "das Taschengeld", example="Sie bekommt jeden Monat Taschengeld."),
        Word("Turkey", "die Türkei", example="Meine Familie kommt ursprünglich aus der Türkei."),
        Word("Accommodation, Board", "die Unterkunft,Unterkünfte", example="Wir haben eine günstige Unterkunft gefunden."),
        Word("To earn something", "etwas verdienen", example="Er verdient gut in seinem neuen Job."),
        Word("To leave something/someone", "etwas/jemanden verlassen", example="Sie musste ihre Heimat verlassen."),
        Word("Food, Board, Meals", "die Verpflegung,-en", example="Die Verpflegung ist im Preis inbegriffen."),
        Word("Why", "warum", example="Warum bist du so spät gekommen?"),
        Word("Because", "weil", example="Ich bleibe zu Hause, weil ich krank bin."),
        Word("To cry", "weinen", example="Das Kind hat lange geweint."),
        Word("Why", "weshalb", example="Weshalb hast du dich nicht gemeldet?"),
        Word("Why", "wieso", example="Wieso hast du das nicht gesagt?"),
        Word("Home", "das Zuhause", example="Endlich bin ich wieder zu Hause."),
        Word("It is true that..., but", "zwar ..., aber", example="Sie ist zwar müde, aber sie hilft trotzdem mit."),
    ],

    "Lebenslinien": [
        Word("High-School Graduation", "das Abitur", example="Sie hat letztes Jahr ihr Abitur gemacht."),
        Word("Beginner (male)", "der Anfänger,-", example="Als Anfänger sollte man langsam üben."),
        Word("Autor (male)", "der Autor,-en", example="Der Autor hat viele bekannte Romane geschrieben."),
        Word("Back then", "damals", example="Damals war das Leben viel einfacher."),
        Word("To be released", "erscheinen", example="Das neue Buch erscheint im Herbst."),
        Word("About, Roughly", "etwa", example="Die Reise dauert etwa drei Stunden."),
        Word("To flee from something", "vor etwas fliehen", example="Viele Menschen mussten vor dem Krieg fliehen."),
        Word("Advanced student (male)", "der Fortgeschrittene,-n", example="Der Kurs ist für Fortgeschrittene gedacht."),
        Word("Complete/ly, Entire/ly", "ganz", example="Ich habe das ganze Buch gelesen."),
        Word("To belong to someone", "jemandem gehören", example="Dieses Haus gehört meiner Familie."),
        Word("Story", "die Geschichte,-n", example="Er erzählte uns eine spannende Geschichte."),
        Word("Still", "immer noch", example="Sie wohnt immer noch in derselben Stadt."),
        Word("To have interest in", "Interesse (an etwas) haben", example="Ich habe großes Interesse an Musik."),
        Word("Knowledge", "die Kenntnis,-se", example="Gute Sprachkenntnisse helfen bei der Arbeitssuche."),
        Word("War", "der Krieg,-e", example="Der Krieg dauerte mehrere Jahre."),
        Word("Artist (male)", "der Künstler,-", example="Der Künstler stellt seine Bilder in einer Galerie aus."),
        Word("Painter (male)", "der Maler,-", example="Der Maler arbeitet an einem neuen Gemälde."),
        Word("Level, Standard", "das Niveau,-s", example="Ihr Deutsch ist schon auf einem hohen Niveau."),
        Word("Postcard", "die Postkarte,-n", example="Ich habe dir eine Postkarte aus Italien geschickt."),
        Word("Prize", "der Preis,-e", example="Sie hat den ersten Preis gewonnen."),
        Word("Actor (male)", "der Schauspieler,-", example="Der Schauspieler spielte die Hauptrolle im Film."),
        Word("Switzerland", "die Schweiz", example="Nächstes Jahr reisen wir in die Schweiz."),
        Word("Since", "seit", example="Ich lerne seit zwei Jahren Deutsch."),
        Word("To die", "sterben", example="Er ist letztes Jahr gestorben."),
        Word("From the beginning", "von Anfang an", example="Ich wusste von Anfang an, dass es schwer wird."),
        Word("Ago", "vor", example="Vor drei Jahren bin ich nach Deutschland gezogen."),
        Word("World", "die Welt", example="Er möchte einmal die ganze Welt bereisen."),
        Word("To return, Come back", "zurück|kommen", example="Sie kommt nächste Woche aus dem Urlaub zurück."),
    ],

}

Vocabulary_Nicos_Weg_A2_1 = {

    "Geld ist für mich...": [
        Word("Than", "als", example="Sie ist älter als ich."),
        Word("To register", "sich an|melden", example="Ich muss mich noch beim Amt anmelden."),
        Word("To spend", "etwas aus|geben", example="Er gibt zu viel Geld für Kleidung aus."),
        Word("Foreigner (male)", "der Ausländer,-", example="Als Ausländer musste er sich erst einleben."),
        Word("Foreigner (female)", "die Ausländerin,-nen", example="Die Ausländerin spricht schon sehr gut Deutsch."),
        Word("Basic bank account", "das Basiskonto,Basiskonten", example="Mit einem Basiskonto kann jeder ein Konto eröffnen."),
        Word("Certificate", "die Bescheinigung,-en", example="Ich brauche eine Bescheinigung von meinem Arbeitgeber."),
        Word("Thankful", "dankbar", example="Ich bin dir sehr dankbar für deine Hilfe."),
        Word("Hence, that is why", "deshalb", example="Es regnet, deshalb bleiben wir zu Hause."),
        Word("Relieved", "erleichtert", example="Sie war erleichtert, als die Prüfung vorbei war."),
        Word("To open something (often for the first time)", "etwas eröffnen", example="Ich möchte ein neues Konto eröffnen."),
        Word("EU citizen (male)", "der EU-Bürger,-", example="Als EU-Bürger braucht er kein Visum."),
        Word("To be pleased, to be glad", "sich freuen", example="Ich freue mich auf das Wochenende."),
        Word("Thrifty, miserly", "geizig", example="Er ist so geizig, dass er nie etwas ausgibt."),
        Word("Banknote", "der Geldschein,-e", example="Sie zahlte mit einem Geldschein."),
        Word("Conversation", "das Gespräch,-e", example="Wir hatten ein langes Gespräch über die Zukunft."),
        Word("Current account, checking account", "das Girokonto,Girokonten", example="Mein Gehalt wird auf mein Girokonto überwiesen."),
        Word("Account", "das Konto,Konten", example="Ich habe kein Geld mehr auf meinem Konto."),
        Word("To be able to afford something", "sich etwas leisten können", example="Wir können uns diesen Urlaub nicht leisten."),
        Word("Coin", "die Münze,-n", example="Er sammelt alte Münzen."),
        Word("Mad/angry at someone", "auf jemanden sauer", example="Sie ist immer noch sauer auf ihren Bruder."),
        Word("Certainly, surely", "sicher", example="Das ist sicher die beste Lösung."),
        Word("To save (some money)", "(etwas) sparen", example="Ich spare jeden Monat etwas Geld."),
        Word("Savings account", "das Sparkonto,Sparkonten", example="Er hat ein Sparkonto für den Notfall."),
        Word("Electricity", "der Strom", example="Der Strom ist diesen Monat teurer geworden."),
        Word("Really?", "wirklich?", example="Wirklich? Das habe ich nicht gewusst."),
        Word("Angry, furious", "wütend", example="Sie war wütend, weil der Bus zu spät kam."),
        Word("To save, to set aside", "etwas zurück|legen", example="Ich lege jeden Monat etwas Geld zurück."),
    ],

    "Mein Bankkonto": [
        Word("To withdraw something", "etwas ab|heben", example="Ich muss noch Geld vom Automaten abheben."),
        Word("Registration", "die Anmeldung,-en", example="Die Anmeldung für den Kurs dauert nur fünf Minuten."),
        Word("In any case, definitely", "auf jeden Fall", example="Ruf mich auf jeden Fall an, wenn du ankommst."),
        Word("To fill out something (i.e., a form)", "etwas aus|füllen", example="Bitte füllen Sie das Formular vollständig aus."),
        Word("Bank clerk (male)", "der Bankangestellte,-n", example="Der Bankangestellte half mir bei der Kontoeröffnung."),
        Word("Bank clerk (female)", "die Bankangestellte,-n", example="Die Bankangestellte war sehr freundlich."),
        Word("ATM, cash machine", "der Geldautomat,-en", example="Der Geldautomat an der Ecke funktioniert nicht."),
        Word("Bank thief (male)", "der Bankräuber,-", example="Der Bankräuber wurde noch am selben Tag gefasst."),
        Word("Bank thief (female)", "die Bankräuberin,-nen", example="Die Bankräuberin konnte fliehen."),
        Word("Cash", "das Bargeld", example="Ich habe leider kein Bargeld dabei."),
        Word("Income", "das Einkommen,-", example="Sein monatliches Einkommen ist nicht sehr hoch."),
        Word("Secure income", "das feste Einkommen", example="Für den Kredit braucht man ein festes Einkommen."),
        Word("Marital status", "der Familienstand", example="Bitte geben Sie Ihren Familienstand an."),
        Word("Form", "das Formular,-e", example="Das Formular muss unterschrieben werden."),
        Word("Fee", "die Gebühr,-en", example="Für die Kontoführung fällt eine Gebühr an."),
        Word("Birthdate", "das Geburtsdatum,Geburtsdaten", example="Bitte tragen Sie Ihr Geburtsdatum ein."),
        Word("Place of birth", "der Geburtsort,-e", example="Mein Geburtsort ist eine kleine Stadt in Spanien."),
        Word("PIN number", "die Geheimzahl,-en", example="Vergiss deine Geheimzahl nicht."),
        Word("Gender", "das Geschlecht,-er", example="Im Formular muss man das Geschlecht angeben."),
        Word("Debit card", "die Girocard,-s", example="Ich bezahle meistens mit meiner Girocard."),
        Word("Loan, credit", "der Kredit,-e", example="Er hat einen Kredit für das neue Auto aufgenommen."),
        Word("Credit card", "die Kreditkarte,-n", example="Kann ich mit Kreditkarte bezahlen?"),
        Word("To lend somebody something", "jemandem etwas leihen", example="Kannst du mir zwanzig Euro leihen?"),
        Word("To mean something/someone", "etwas/jemanden meinen", example="Ich glaube, sie meint dich."),
        Word("What do you mean by that?", "was meinst du damit?", example="Was meinst du damit genau?"),
        Word("To inquire", "nach|fragen", example="Ich werde bei der Bank nachfragen."),
        Word("Nationality", "die Nationalität,-en", example="Welche Nationalität hast du?"),
        Word("By, via", "per", example="Die Zahlung erfolgt per Überweisung."),
        Word("Via post", "per Post", example="Die Karte wird Ihnen per Post zugeschickt."),
        Word("PIN", "die PIN-Nummer,-n", example="Gib bitte deine PIN-Nummer ein."),
        Word("To overdraw (money)", "etwas überziehen", example="Bitte überzieh dein Konto nicht wieder."),
        Word("Superior (male)", "der Vorgesetzte,-n", example="Mein Vorgesetzter ist sehr verständnisvoll."),
        Word("Superior (female)", "die Vorgesetzte,-n", example="Ich muss das mit meiner Vorgesetzten besprechen."),
    ],

    "Rechnungen": [
        Word("To debit or to charge something", "etwas ab|buchen", example="Die Miete wird automatisch abgebucht."),
        Word("To be deducted", "ab|gehen", example="Von meinem Gehalt gehen Steuern ab."),
        Word("To pay attention to something/somebody", "auf etwas/jemanden achten", example="Achte bitte auf deine Ausgaben."),
        Word("To leave something on, to leave something running", "etwas an|lassen", example="Du hast das Licht wieder angelassen."),
        Word("Kind, type, form", "die Art,-en", example="Das ist eine seltsame Art, Probleme zu lösen."),
        Word("To turn something off", "etwas aus|schalten", example="Bitte schalte den Fernseher aus."),
        Word("To attest something", "etwas bescheinigen", example="Der Arzt hat mir die Krankheit bescheinigt."),
        Word("Amount", "der Betrag,Beträge", example="Der Betrag wurde bereits überwiesen."),
        Word("Standing order", "der Dauerauftrag,Daueraufträge", example="Ich habe einen Dauerauftrag für die Miete eingerichtet."),
        Word("To enter something (like a password)", "etwas ein|geben", example="Bitte geben Sie Ihr Passwort ein."),
        Word("To enter or apply", "ein|gehen", example="Die Bewerbung ist gestern eingegangen."),
        Word("To set something up (physical/technical)", "etwas ein|richten", example="Wir haben das neue Büro eingerichtet."),
        Word("To deposit something", "etwas ein|zahlen", example="Ich möchte Geld auf mein Konto einzahlen."),
        Word("Recipient (male)", "der Empfänger,-", example="Bitte geben Sie den Namen des Empfängers an."),
        Word("To remind someone of something", "jemanden an etwas erinnern", example="Erinnere mich bitte an den Termin."),
        Word("Reminder", "die Erinnerung,-en", example="Ich habe eine Erinnerung für morgen eingestellt."),
        Word("Gas", "das Gas", example="Die Gaspreise sind letztes Jahr stark gestiegen."),
        Word("To be in the minus, in the red", "im Minus sein", example="Mein Konto ist leider im Minus."),
        Word("To be in the plus, in the black", "im Plus sein", example="Am Monatsende bin ich meistens im Plus."),
        Word("Account holder (male)", "der Kontoinhaber,-", example="Nur der Kontoinhaber darf Geld abheben."),
        Word("Account balance", "der Kontostand,Kontostände", example="Ich sollte meinen Kontostand öfter überprüfen."),
        Word("To take out a loan, to borrow (loan, money)", "einen Kredit auf|nehmen", example="Sie mussten einen Kredit aufnehmen, um das Haus zu kaufen."),
        Word("To look after, take care of something/somebody", "sich um etwas/jemanden kümmern", example="Ich kümmere mich um die Rechnungen."),
        Word("Direct debit", "die Lastschrift,-en", example="Die Zahlung erfolgt per Lastschrift."),
        Word("Light", "das Licht,-er", example="Mach bitte das Licht aus, wenn du gehst."),
        Word("Warning, overdue notice", "die Mahnung,-en", example="Ich habe eine Mahnung wegen der unbezahlten Rechnung bekommen."),
        Word("Receipt, bill", "die Quittung,-en", example="Bitte heben Sie die Quittung gut auf."),
    ],

    "Am Bankautomaten": [
        Word("Cancellation, demolition, abortion", "der Abbruch,Abbrüche", example="Nach dem Abbruch der Transaktion war das Geld weg."),
        Word("To print out something", "etwas aus|drucken", example="Ich muss noch den Kontoauszug ausdrucken."),
        Word("To choose something/somebody", "etwas/jemanden aus|wählen", example="Wählen Sie bitte eine Sprache aus."),
        Word("Payout, withdrawal", "die Auszahlung,-en", example="Die Auszahlung dauert einige Minuten."),
        Word("Vending machine", "der Automat,-en", example="Der Automat nimmt keine Scheine an."),
        Word("Confirmation", "die Bestätigung,-en", example="Ich habe eine Bestätigung per E-Mail erhalten."),
        Word("Data (information)", "die Daten", example="Bitte überprüfen Sie Ihre Daten."),
        Word("To print (something)", "(etwas) drucken", example="Kannst du das Dokument bitte drucken?"),
        Word("To press something", "auf etwas drücken", example="Drücken Sie auf die grüne Taste."),
        Word("To enter something (like a PIN)", "etwas ein|geben", example="Geben Sie bitte Ihre PIN ein."),
        Word("Deposit, (in)payment", "die Einzahlung,-en", example="Die Einzahlung war erfolgreich."),
        Word("An error message", "die Fehlermeldung,-en", example="Der Automat zeigte eine Fehlermeldung an."),
        Word("To come out", "heraus|kommen", example="Das Geld kommt gleich aus dem Automaten heraus."),
        Word("Account statement", "der Kontoauszug,Kontoauszüge", example="Ich hole mir jeden Monat meinen Kontoauszug."),
        Word("Correction", "die Korrektur,-en", example="Eine Korrektur der Eingabe war leider nicht möglich."),
        Word("Possible", "möglich", example="Ist eine Barzahlung hier möglich?"),
        Word("PIN", "die PIN,-s", example="Bitte geben Sie Ihre PIN ein."),
        Word("Semester(s)", "das Semester,-", example="Das neue Semester beginnt im April."),
        Word("To stick inside", "stecken", example="Steck die Karte bitte richtig herum in den Automaten."),
        Word("Button, key (on a keyboard)", "die Taste,-n", example="Drücken Sie die grüne Taste zum Bestätigen."),
        Word("To click on, to tap on", "auf etwas tippen", example="Tippen Sie auf den Bildschirm, um fortzufahren."),
        Word("Lastly, finally", "zuletzt", example="Zuletzt müssen Sie noch Ihre Unterschrift eingeben."),
    ],

}

Vocabulary_Nicos_Weg_A2_2 = {

    "Familiengeschichten": [
        Word("To leave, to dip out, to scram", "ab|hauen", "Images/Vocabulary_Nicos_Weg_A2_2/abhauen", example="Er ist mit siebzehn von zu Hause abgehauen."),
        Word("Besides", "außerdem", example="Ich habe keine Zeit, außerdem bin ich müde."),
        Word("At", "bei", example="Ich wohne bei meinen Eltern."),
        Word("Grown-up, mature", "erwachsen", "Images/Vocabulary_Nicos_Weg_A2_2/erwachsen", example="Meine Tochter ist jetzt erwachsen."),
        Word("With", "mit", example="Ich gehe mit meinem Bruder einkaufen."),
        Word("To push something, to move something", "etwas schieben", "Images/Vocabulary_Nicos_Weg_A2_2/schieben", example="Kannst du mir helfen, das Auto zu schieben?"),
        Word("Single person", "der Single,-s", example="Er ist schon lange Single."),
        Word("To play with somebody", "mit jemandem spielen", example="Die Kinder spielen mit ihren Cousins."),
        Word("Strict", "streng", "Images/Vocabulary_Nicos_Weg_A2_2/streng", example="Mein Vater war immer sehr streng."),
        Word("To forget something/someone", "etwas/jemanden vergessen", example="Ich habe seinen Namen leider vergessen."),
        Word("To listen to someone", "jemandem zu|hören", "Images/Vocabulary_Nicos_Weg_A2_2/zuhören", example="Bitte hör mir kurz zu."),
    ],

    "Personen beschreiben": [
        Word("First, in the beginning", "am Anfang", example="Am Anfang war sie sehr schüchtern."),
        Word("Beard", "der Bart,Bärte", example="Mein Opa hat einen langen Bart."),
        Word("To describe something/somebody", "etwas/jemanden beschreiben", "Images/Vocabulary_Nicos_Weg_A2_2/beschreiben", example="Kannst du den Täter beschreiben?"),
        Word("Blonde", "blond", "Images/Vocabulary_Nicos_Weg_A2_2/blond", example="Sie hat lange, blonde Haare."),
        Word("All the way, completely", "ganz", example="Ich bin ganz sicher, dass er recht hat."),
        Word("Heart", "das Herz,-en", "Images/Vocabulary_Nicos_Weg_A2_2/herz", example="Sein Herz schlug vor Aufregung schnell."),
        Word("To smile", "lächeln", "Images/Vocabulary_Nicos_Weg_A2_2/lächeln", example="Sie lächelte, als sie mich sah."),
        Word("Song", "das Lied,-er", example="Dieses Lied gefällt mir sehr."),
        Word("Note", "die Notiz,-en", "Images/Vocabulary_Nicos_Weg_A2_2/notiz", example="Ich habe mir eine Notiz gemacht."),
        Word("Open, open-minded", "offen", example="Er ist sehr offen für neue Ideen."),
        Word("Tolerant, open-minded", "tolerant", example="Meine Nachbarn sind sehr tolerant."),
        Word("To translate something", "etwas übersetzen", "Images/Vocabulary_Nicos_Weg_A2_2/übersetzen", example="Kannst du diesen Satz übersetzen?"),
        Word("Preparation", "die Vorbereitung,-en", example="Die Vorbereitung auf die Prüfung dauert lange."),
        Word("Repetition", "die Wiederholung,-en", example="Wiederholung hilft beim Sprachenlernen."),
    ],

    "Generationen": [
        Word("Geriatric nurse (male)", "der Altenpfleger,-", "Images/Vocabulary_Nicos_Weg_A2_2/altenpfleger", example="Mein Onkel arbeitet als Altenpfleger."),
        Word("Geriatric nurse (female)", "die Altenpflegerin,-nen", example="Die Altenpflegerin kümmert sich liebevoll um die Bewohner."),
        Word("Outpatient", "ambulant", example="Meine Oma wird ambulant betreut."),
        Word("To accompany something/someone, to support sth/sb", "etwas/jemanden begleiten", "Images/Vocabulary_Nicos_Weg_A2_2/begleiten", example="Ich begleite meinen Vater zum Arzt."),
        Word("Complaints, symptoms", "die Beschwerden", "Images/Vocabulary_Nicos_Weg_A2_2/beschwerden", example="Er hat schon seit Wochen Beschwerden im Rücken."),
        Word("Refugee home", "das Flüchtlingsheim,-e", example="In der Stadt gibt es ein neues Flüchtlingsheim."),
        Word("Walking stick", "der Gehstock,Gehstöcke", "Images/Vocabulary_Nicos_Weg_A2_2/gehstock", example="Ohne seinen Gehstock kann er kaum laufen."),
        Word("Hearing aid", "das Hörgerät,-e", "Images/Vocabulary_Nicos_Weg_A2_2/hörgerät", example="Mein Opa trägt seit letztem Jahr ein Hörgerät."),
    ],

    "Alten- und Pflegeheim": [
        Word("Retirement home", "das Altenheim,-e", "Images/Vocabulary_Nicos_Weg_A2_2/altenheim", example="Meine Großmutter lebt seit einem Jahr im Altenheim."),
        Word("Excellent", "ausgezeichnet", "Images/Vocabulary_Nicos_Weg_A2_2/ausgezeichnet", example="Das Essen im Heim ist ausgezeichnet."),
        Word("That's why, for that reason", "deswegen", example="Sie ist krank, deswegen bleibt sie im Bett."),
        Word("Lonely", "einsam", "Images/Vocabulary_Nicos_Weg_A2_2/einsam", example="Nach dem Umzug fühlte er sich sehr einsam."),
        Word("Energy, power", "die Energie,-n", example="Nach dem Urlaub habe ich viel Energie."),
        Word("Reason", "der Grund,Gründe", example="Der Grund für seinen Umzug war die Arbeit."),
        Word("Mobile, portable", "mobil", example="Mit dem Rollator ist sie wieder mobil."),
        Word("Retiree, pensioner (male)", "der Rentner,-", "Images/Vocabulary_Nicos_Weg_A2_2/rentner", example="Der Rentner geht jeden Morgen spazieren."),
        Word("Retiree, pensioner (female)", "die Rentnerin,-nen", example="Die Rentnerin engagiert sich ehrenamtlich."),
        Word("Weak", "schwach", example="Nach der Krankheit fühlte er sich sehr schwach."),
        Word("Oh, Pardon!", "Oh, Verzeihung!", example="Oh, Verzeihung! Das wollte ich nicht."),
    ],

}

Vocabulary_Nicos_Weg_A2_3 = {

    "Wohngemeinschaft": [
        Word("Iron (for clothing)", "das Bügeleisen,-", "Images/Vocabulary_Nicos_Weg_A2_3/bügeleisen", example="Das Bügeleisen ist noch heiß."),
        Word("To iron (something)", "(etwas) bügeln", "Images/Vocabulary_Nicos_Weg_A2_3/bügeln", example="Ich bügle heute meine Hemden."),
        Word("Brush, scrubber", "die Bürste,-n", "Images/Vocabulary_Nicos_Weg_A2_3/bürste", example="Die Bürste liegt neben dem Waschbecken."),
        Word("Chaos", "das Chaos", example="In der Küche herrscht totales Chaos."),
        Word("To move in", "ein|ziehen", "Images/Vocabulary_Nicos_Weg_A2_3/einziehen", example="Wir ziehen nächste Woche in die neue Wohnung ein."),
        Word("To sweep (something)", "(etwas) fegen", "Images/Vocabulary_Nicos_Weg_A2_3/fegen", example="Kannst du bitte den Flur fegen?"),
        Word("Rag, cloth", "der Lappen,-", example="Wisch den Tisch mit einem Lappen ab."),
        Word("Empty", "leer", example="Der Kühlschrank ist komplett leer."),
        Word("Waste bin", "der Mülleimer,-", "Images/Vocabulary_Nicos_Weg_A2_3/mülleimer", example="Der Mülleimer in der Küche ist voll."),
        Word("Garbage can", "die Mülltonne,-n", "Images/Vocabulary_Nicos_Weg_A2_3/mülltonne", example="Die Mülltonne steht vor dem Haus."),
        Word("Deposit bottle", "die Pfandflasche,-n", "Images/Vocabulary_Nicos_Weg_A2_3/pfandflasche", example="Ich bringe die Pfandflaschen zum Supermarkt zurück."),
        Word("Plant", "die Pflanze,-n", "Images/Vocabulary_Nicos_Weg_A2_3/pflanze", example="Die Pflanze braucht mehr Wasser."),
        Word("To take sth/sb out(side)", "etwas/jemanden raus|bringen", example="Kannst du den Müll rausbringen?"),
        Word("To stay calm/quiet", "ruhig bleiben", example="Bitte bleib ruhig, alles wird gut."),
        Word("To clean up", "sauber machen", "Images/Vocabulary_Nicos_Weg_A2_3/sauber_machen", example="Wir müssen das Wohnzimmer sauber machen."),
        Word("To vacuum", "saugen", "Images/Vocabulary_Nicos_Weg_A2_3/saugen", example="Ich sauge jeden Samstag die Wohnung."),
        Word("Sponge", "der Schwamm,Schwämme", "Images/Vocabulary_Nicos_Weg_A2_3/schwamm", example="Der Schwamm liegt in der Spüle."),
        Word("Self, yourself", "selber/selbst", example="Das habe ich selber gemacht."),
        Word("Dust", "der Staub", "Images/Vocabulary_Nicos_Weg_A2_3/staub", example="Auf dem Regal liegt viel Staub."),
        Word("To dust, to wipe away dust", "Staub wischen", example="Ich muss noch Staub wischen."),
        Word("To dry sth", "etwas trocknen", example="Kannst du das Geschirr trocknen?"),
        Word("Full, filled", "voll", example="Die Waschmaschine ist voll."),
        Word("To take sth/sb away", "etwas/jemanden weg|bringen", example="Ich bringe die alten Möbel weg."),
        Word("To dust, to wipe, to mop", "wischen", "Images/Vocabulary_Nicos_Weg_A2_3/wischen", example="Ich wische gerade den Boden."),
    ],

    "Nachbarschaft": [
        Word("To lock something", "etwas ab|schließen", example="Ich schließe die Tür ab, bevor ich gehe."),
        Word("To change", "sich ändern", example="Das Wetter ändert sich schnell"),
        Word("To say thank you to someone", "sich bei jemandem bedanken", example="Ich möchte mich bei dir bedanken."),
        Word("Directly, immediately", "direkt", example="Wir gehen direkt nach Hause."),
        Word("Celebration, party", "das Fest,-e", "Images/Vocabulary_Nicos_Weg_A2_3/feste", example="Wir feiern ein großes Fest im Garten."),
        Word("Across the way, opposite", "gegenüber", "Images/Vocabulary_Nicos_Weg_A2_3/gegenüber", example="Die Bäckerei liegt gegenüber von der Schule."),
        Word("House rules", "die Hausordnung,-en", example="Bitte lies dir die Hausordnung genau durch."),
        Word("To help", "jemandem bei etwas helfen", example="Kannst du mir bei den Hausaufgaben helfen?"),
        Word("Neighborhood", "die Nachbarschaft,-en", example="Wir wohnen in einer ruhigen Nachbarschaft."),
        Word("Next door", "nebenan", "Images/Vocabulary_Nicos_Weg_A2_3/nebenan", example="Unsere Nachbarn wohnen direkt nebenan."),
        Word("To show consideration/concern for sth/sb", "Rücksicht auf etwas/jemanden nehmen", example="Bitte nimm Rücksicht auf die anderen Mieter."),
        Word("To play with sb", "mit jemandem spielen", example="Die Kinder spielen mit den Nachbarskindern."),
        Word("To speak with sb", "mit jemandem sprechen", "Images/Vocabulary_Nicos_Weg_A2_3/mit_jemandem_sprechen", example="Ich möchte kurz mit dir sprechen."),
        Word("To complain to sb about sth/sb", "sich bei jemandem über etwas/jemanden beschweren", "Images/Vocabulary_Nicos_Weg_A2_3/beschweren", example="Sie hat sich beim Vermieter über den Lärm beschwert."),
        Word("To argue with someone", "sich mit jemandem streiten", "Images/Vocabulary_Nicos_Weg_A2_3/streiten", example="Ich streite mich oft mit meinem Bruder."),
        Word("Stairwell", "das Treppenhaus,Treppenhäuser", "Images/Vocabulary_Nicos_Weg_A2_3/treppenhaus", example="Im Treppenhaus ist es sehr laut."),
        Word("Impolite", "unhöflich", example="Es war unhöflich, nicht zu grüßen."),
        Word("When, if", "wenn", example="Wenn es regnet, bleiben wir zu Hause."),
    ],

    "Kinder": [
        Word("Single parent", "alleinerziehend", example="Meine Schwester ist alleinerziehend und hat zwei Kinder."),
        Word("Single parent (male)", "der Alleinerziehende,-n", example="Als Alleinerziehender hat er wenig freie Zeit."),
        Word("Everything OK?", "Alles in Ordnung?", example="Alles in Ordnung? Du siehst müde aus."),
        Word("To offer, to serve", "etwas an|bieten", example="Die Kita bietet auch Betreuung am Wochenende an."),
        Word("Offering, range", "das Angebot,-e", example="Das Angebot der Schule ist sehr vielfältig."),
        Word("To maintain sth, to look after sth/sb", "etwas/jemanden betreuen", example="Meine Mutter betreut die Kinder am Nachmittag."),
        Word("Care", "die Betreuung", example="Die Betreuung in der Kita ist kostenlos."),
        Word("That means", "das heißt", example="Er kommt später, das heißt, wir müssen warten."),
        Word("To lose one's nerves, to lose one's cool", "die Nerven verlieren", example="Bei so viel Stress verliere ich schnell die Nerven."),
        Word("To have a baby", "ein Kind bekommen", example="Meine Schwester hat letzten Monat ein Kind bekommen."),
        Word("To end", "enden", example="Die Schule endet um 13 Uhr."),
        Word("To rear sb, to nurture sb, to educate sb", "jemanden erziehen", example="Es ist nicht einfach, drei Kinder allein zu erziehen."),
        Word("Kindergarten teacher (male)", "der Erzieher,-", example="Der Erzieher spielt jeden Tag mit den Kindern."),
        Word("Kindergarten teacher (female)", "die Erzieherin,-nen", example="Die Erzieherin kümmert sich liebevoll um die Kleinen."),
        Word("Voluntary, volunteer, voluntarily", "freiwillig", example="Die Teilnahme an dem Kurs ist freiwillig."),
        Word("Elementary school", "die Grundschule,-n", example="Meine Tochter geht seit letztem Jahr in die Grundschule."),
        Word("Group", "die Gruppe,-n", example="Die Kinder sind in kleine Gruppen eingeteilt."),
        Word("Daycare center, day nursery", "die Kindertagesstätte,-n", example="Unser Sohn geht seit September in die Kindertagesstätte."),
        Word("Some, certain", "mancher,manche,manches", example="Manche Eltern arbeiten Teilzeit, um mehr Zeit mit den Kindern zu haben."),
        Word("Pregnant", "schwanger", example="Meine Kollegin ist im sechsten Monat schwanger."),
        Word("Difficult", "schwierig", example="Die Prüfung war sehr schwierig."),
        Word("Daycare, childminder", "die Tagesmutter,Tagesmütter", example="Die Tagesmutter betreut vier Kinder in ihrer Wohnung."),
        Word("To be together", "zusammen sein", example="Am Wochenende sind wir immer zusammen."),
    ],

    "Anders als ihr": [
        Word("To move out", "aus|ziehen", example="Meine Tochter zieht nächsten Monat aus."),
        Word("Special", "besonderer,besondere,besonderes", example="Das war ein ganz besonderer Tag für mich."),
        Word("Resident (male)", "der Bewohner,-", example="Die Bewohner des Hauses trafen sich im Garten."),
        Word("Resident (female)", "die Bewohnerin,-nen", example="Die Bewohnerin beschwerte sich über den Lärm."),
        Word("Previously, in the past", "früher", example="Früher habe ich in einer WG gewohnt."),
        Word("More frequently, more often", "öfter", example="Wir sollten uns öfter treffen."),
        Word("Difference, distinction", "der Unterschied,-e", example="Der Unterschied zwischen den beiden ist groß."),
        Word("Related", "verwandt", example="Wir sind nicht verwandt, aber gute Freunde."),
        Word("To weigh", "wiegen", example="Das Paket wiegt fast fünf Kilo."),
        Word("To move to", "ziehen", example="Sie zieht nächstes Jahr nach Berlin."),
        Word("To live (together) with sb", "mit jemandem zusammen|wohnen", example="Ich wohne mit meiner Schwester zusammen."),
    ]
}

Vocabulary_Nicos_Weg_A2_4 = {

    "Unterwegs": [
        Word("To be canceled", "aus|fallen", example="Der Flug ist wegen des Sturms ausgefallen."),
        Word("Abroad", "das Ausland", example="Sie arbeitet seit zwei Jahren im Ausland."),
        Word("Respondent (male)", "der Befragte,-n", example="Der Befragte antwortete sehr ausführlich."),
        Word("Result", "das Ergebnis,-se", example="Das Ergebnis der Umfrage war überraschend."),
        Word("Long-distance travel, overseas travel", "die Fernreise,-n", example="Eine Fernreise nach Asien ist ihr großer Traum."),
        Word("Flight", "der Flug,Flüge", example="Der Flug nach Berlin dauert nur eine Stunde."),
        Word("Business trip", "die Geschäftsreise,-n", example="Er ist diese Woche auf Geschäftsreise."),
        Word("Group trip", "die Gruppenreise,-n", example="Wir haben an einer Gruppenreise nach Italien teilgenommen."),
        Word("To fly to", "hin|fliegen", example="Wir fliegen nächste Woche nach Spanien hin."),
        Word("Flight (to somewhere)", "der Hinflug,Hinflüge", example="Der Hinflug war leider stark verspätet."),
        Word("To get sth, to have", "etwas kriegen", example="Hast du schon eine Antwort gekriegt?"),
        Word("Culture", "die Kultur,-en", example="Die japanische Kultur interessiert mich sehr."),
        Word("Place", "der Ort,-e", example="Das ist ein sehr schöner Ort für den Urlaub."),
        Word("Practical", "praktisch", example="Ein Rucksack ist für Reisen sehr praktisch."),
        Word("Private", "privat", example="Das ist eine private Angelegenheit."),
        Word("Percent", "das Prozent,-e", example="Fünfzig Prozent der Befragten reisen gerne allein."),
        Word("Travel agency", "das Reisebüro,-s", example="Wir haben die Reise über ein Reisebüro gebucht."),
        Word("Return flight", "der Rückflug,Rückflüge", example="Unser Rückflug geht morgen früh."),
        Word("City trip", "der Städteurlaub,-e", example="Ein Städteurlaub in Paris steht schon lange auf unserer Liste."),
        Word("Beach vacation", "der Strandurlaub,-e", example="Im Sommer machen wir immer einen Strandurlaub."),
        Word("Ticket (public transportation)", "das Ticket,-s", example="Hast du schon ein Ticket für den Zug gekauft?"),
        Word("On the road", "unterwegs", example="Wir sind schon seit acht Stunden unterwegs."),
        Word("To fly back", "zurück|fliegen", example="Wir fliegen am Sonntag zurück."),
    ],

    "Im Hotel": [
        Word("To turn right/left", "rechts/links ab|biegen", example="Biegen Sie an der nächsten Kreuzung rechts ab."),
        Word("To accept sth/sb", "etwas/jemanden akzeptieren", example="Wir akzeptieren nur Bargeld als Zahlungsmittel."),
        Word("Pleasant", "angenehm", example="Der Aufenthalt im Hotel war sehr angenehm."),
        Word("Residence, stay", "der Aufenthalt,-e", example="Der Aufenthalt in der Stadt war sehr kurz."),
        Word("Task, duty", "die Aufgabe,-n", example="Die Aufgabe des Hotels ist es, den Gästen einen angenehmen Aufenthalt zu bieten."),
        Word("ID, ID card", "der Ausweis,-e", example="Bitte zeigen Sie Ihren Ausweis an der Rezeption."),
        Word("Bathtub", "die Badewanne,-n", example="Die Badewanne im Hotelzimmer ist sehr groß."),
        Word("To need sth", "etwas benötigen", example="Wir benötigen ein Zimmer für zwei Nächte."),
        Word("Cocktail", "der Cocktail,-s", example="Der Cocktail an der Hotelbar war sehr lecker."),
        Word("Double room", "das Doppelzimmer,-", example="Wir haben ein Doppelzimmer mit Balkon gebucht."),
        Word("To answer a question", "eine Frage beantworten", example="Können Sie mir bitte diese Frage beantworten?"),
        Word("Single room", "das Einzelzimmer,-", example="Ich habe ein Einzelzimmer für eine Nacht reserviert."),
        Word("Relaxing, restful", "erholsam", example="Der Urlaub am Meer war sehr erholsam."),
        Word("Breakfast buffet", "das Frühstücksbuffet,-s", example="Das Frühstücksbuffet im Hotel ist sehr umfangreich."),
        Word("Hallway, corridor", "der Gang,Gänge", example="Der Gang zum Zimmer ist sehr lang."),
        Word("Then, after that, shortly thereaftere", "gleich", example="Wir gehen gleich zum Strand."),
        Word("Pet", "das Haustier,-e", example="Wir haben ein kleines Haustier, einen Hund."),
        Word("Hotel manager (male)", "der Hotelmanager,-", example="Der Hotelmanager kümmert sich um die Gäste."),
        Word("Hotel manager (female)", "die Hotelmanagerin,-nen", example="Die Hotelmanagerin ist sehr freundlich."),
        Word("Included", "inbegriffen", example="Das Frühstück ist im Preis inbegriffen."),
        Word("Guesthouse", "die Pension,-en", example="Wir haben in einer kleinen Pension übernachtet."),
        Word("Passport", "der Reisepass,Reisepässe", example="Bitte zeigen Sie Ihren Reisepass an der Rezeption."),
        Word("Reception, front desk", "die Rezeption,-en", example="Die Rezeption ist rund um die Uhr besetzt."),
        Word("Front desk clerk, receptionist (male)", "der Rezeptionist,-en", example="Der Rezeptionist hat uns freundlich empfangen."),
        Word("Front desk clerk, receptionist (female)", "die Rezeptionistin,-nen", example="Die Rezeptionistin hat uns die Schlüssel für das Zimmer gegeben."),
        Word("Housekeepking (male)", "der Roomboy,-s", example="Der Roomboy hat das Zimmer gereinigt."),
        Word("Sauna", "die Sauna,Saunen", example="Die Sauna im Hotel ist sehr entspannend."),
        Word("Dormitory", "der Schlafsaal,Schlafsäle", example="Wir haben in einem Schlafsaal übernachtet."),
        Word("To ensure sth, to provide for sth", "für etwas sorgen", example="Das Hotel sorgt für einen angenehmen Aufenthalt der Gäste."),
        Word("Stressful", "stressig", example="Die Arbeit in der Rezeption kann manchmal sehr stressig sein."),
        Word("Overnight stay", "die Übernachtung,-en", example="Die Übernachtung im Hotel war sehr komfortabel."),
        Word("Housekeeping (female)", "die Zimmermädchen,-", example="Die Zimmermädchen reinigen die Hotelzimmer jeden Tag."),
    ],

    
}    

Vocabulary_Nicos_Weg_A2_7 = {

    "Immer und überall": [
        Word("App", "die App,-s", example="Ich habe eine neue App auf meinem Smartphone installiert."),
        Word("Fault,broken", "defekt"),
        Word("To download sth", "etwas down|loaden", example="Ich habe die neue Version der App downgeloadet"),
        Word("To reach sb, to get in touch with sb", "jemanden erreichen", example="Ich konnte ihn gestern nicht erreichen."),
        Word("Freedom", "die Freiheit,-en"),
        Word("To google sb/sth", "etwas/jemanden googeln", example="Ich habe den Namen gegoogelt, um mehr Informationen zu finden."),
        Word("To download sth", "etwas herunter|laden"),
        Word("Camera", "die Kamera,-s"),
        Word("Headphones", "der Kopfhörer,-"),
        Word("Passion", "die Leidenschaft,-en"),
        Word("To like (only on social media)", "etwas liken"),
        Word("To send an email (to sb)", "(jemandem etwas) mailen"),
        Word("To use sth", "etwas nutzen"),
        Word("Offline", "offline"),
        Word("Online", "online"),
        Word("Flat, drained, dull", "platt"),
        Word("To post sth", "etwas posten"),
        Word("Tire", "der Reifen,-"),
        Word("To skype", "skypen"),
        Word("Smartphone", "das Smartphone,-s"),
        Word("Social network", "das soziale Netzwerk, die sozialen Netzwerke"),
        Word("To surf", "surfen"),
        Word("Tablet computer", "das Tablet,-s"),
        Word("To share", "etwas teilen"),
        Word("Everywhere, all over", "überall"),
        Word("Advertising agency", "die Werbagentur,-en"),
        Word("Newspaper", "die Zeitung,-en"),
    ],

    
}

Grammatik_Aktiv = {

    "Reflexive (und reziproke) Verben": [
        Word("To comb (oneself)", "sich kämmen", example="Ich kämme mich jeden Morgen vor dem Frühstück."),
        Word("To get dressed", "sich an|ziehen", example="Zieh dich schnell an, wir sind spät dran."),
        Word("To wash (oneself)", "sich waschen", example="Ich wasche mich immer nach dem Sport."),
        Word("To undress (oneself)", "sich aus|ziehen", example="Er zog sich aus und ging ins Bett."),
        Word("To injure (oneself)", "sich verletzen", example="Sie hat sich beim Fußballspielen verletzt."),
        Word("To introduce (oneself)", "sich vor|stellen", example="Darf ich mich kurz vorstellen?"),
        Word("To cut (oneself)", "sich schneiden", example="Ich habe mich beim Kochen geschnitten."),
        Word("To entertain, chat (oneself)", "sich unterhalten", example="Wir haben uns lange über die Reise unterhalten."),
        Word("To get a doctor's note", "sich krankschreiben lassen", example="Er hat sich für zwei Tage krankschreiben lassen."),
        Word("To remember/recall (oneself)", "sich erinnern an", example="Ich erinnere mich gut an meine Kindheit."),
        Word("To prepare (oneself)", "sich vor|bereiten", example="Sie bereitet sich auf die Prüfung vor."),
        Word("To dress up/make oneself look nice", "sich schick machen", example="Sie macht sich schick für die Party heute Abend."),
        Word("To get lost (on foot)", "sich verlaufen", example="Wir haben uns im Wald verlaufen."),
        Word("To argue/fight (about something)", "sich streiten (über etwas)", example="Meine Eltern streiten sich oft über Geld."),
        Word("To apologize (to someone)", "sich entschuldigen (bei jemandem)", example="Ich habe mich bei ihr entschuldigt."),
        Word("To fall in love (with somebody)", "sich verlieben (in jemanden)", example="Er hat sich in seine Kollegin verliebt."),
        Word("To separate/split up (from somebody)", "sich trennen (von jemandem)", example="Sie haben sich nach zehn Jahren getrennt."),
        Word("To enjoy oneself", "sich amüsieren", example="Die Kinder haben sich auf der Party gut amüsiert."),
    ],

    "Reflexivpronomen im Dativ": [
        Word("To comb one's (specific part)", "sich etwas kämmen", example="Sie kämmt sich die Haare vor dem Spiegel."),
        Word("To put on (clothing)", "sich etwas an|ziehen", example="Zieh dir bitte eine Jacke an, es ist kalt."),
        Word("To wash one's (specific body part)", "sich etwas waschen", example="Wasch dir bitte die Hände vor dem Essen."),
        Word("To take off (clothing)", "sich etwas aus|ziehen", example="Er zog sich die Schuhe aus, bevor er hineinging."),
        Word("To injure (specific body part)", "sich etwas verletzen", example="Ich habe mir beim Skifahren das Bein verletzt."),
        Word("To buy something for oneself", "sich etwas kaufen", example="Ich möchte mir ein neues Fahrrad kaufen."),
        Word("To wish oneself something", "sich etwas wünschen", example="Was wünschst du dir zum Geburtstag?"),
        Word("To choose something for oneself", "sich etwas aus|suchen", example="Sie hat sich ein schönes Kleid ausgesucht."),
        Word("To imagine something", "sich etwas vor|stellen", example="Ich kann mir das nur schwer vorstellen."),
        Word("To plan something for oneself", "sich etwas vor|nehmen", example="Ich habe mir vorgenommen, mehr Sport zu treiben."),
        Word("To break, fracture one's (specific body part)", "sich etwas brechen", example="Er hat sich beim Sturz den Arm gebrochen."),
        Word("To worry about something", "sich Sorgen um etwas machen", example="Mach dir keine Sorgen um die Prüfung."),
        Word("To cut one's (specific body part)", "sich etwas schneiden", example="Sie hat sich beim Rasieren den Finger geschnitten."),
        Word("To have/get something made/done (for oneself)", "sich etwas machen lassen", example="Ich lasse mir die Haare schneiden."),
        Word("To paint/polish one's (nails)", "sich die Nägel lackieren", example="Sie lackiert sich heute Abend die Nägel."),
    ],

    "Trennbare und untrennbare Verben": [
        Word("To buy something", "ein|kaufen", example="Ich gehe heute Nachmittag im Supermarkt einkaufen."),
        Word("To call somebody", "an|rufen", example="Ich rufe meinen Freund an."),
        Word("To turn off (electronics), to arrange/agree on (an appointment)", "aus|machen", example="Ich mache den Fernseher aus."),
        Word("To invite somebody", "ein|laden", example="Ich lade meine Freunde zu einem Picknick ein."),
        Word("To tidy up, to clean up", "auf|räumen", example="Ich räume mein Zimmer auf."),
        Word("To enter, get in, board", "ein|steigen", example="Ich steige in den Bus ein."),
        Word("To get out, exit", "aus|steigen", example="Ich steige aus dem Bus aus."),
        Word("To start/turn on (engines, cars)", "an|springen", example="Der Motor springt an."),

        # --- trennbar ---
        Word("To depart", "ab|fahren", example="Der Zug fährt um acht Uhr ab."),
        Word("To stop something, to halt", "etwas an|halten", example="Der Bus hält an der Haltestelle an."),
        Word("To arrive", "an|kommen", example="Wir kommen um sechs Uhr an."),
        Word("To inform, to notify", "jemandem etwas mit|teilen", example="Ich habe ihm mitgeteilt, dass ich später komme."),
        Word("To watch TV", "fern|sehen", example="Am Abend sehe ich gerne fern."),
        Word("To bring along", "etwas mit|bringen", example="Kannst du etwas zu essen mitbringen?"),
        Word("To fall asleep", "ein|schlafen", example="Ich bin gestern früh eingeschlafen."),
        Word("To turn on (a device)", "etwas an|machen", example="Mach bitte die Waschmaschine an."),
        Word("To pick up, to collect", "etwas ab|holen", example="Ich hole die Kleidung aus der Reinigung ab."),
        Word("To prepare something", "etwas vor|bereiten", example="Ich bereite das Essen für die Party vor."),
        Word("To get up", "auf|stehen", example="Ich stehe jeden Tag um sieben Uhr auf."),
        Word("To drive away, to leave", "weg|fahren", example="Wir fahren morgen früh weg."),
        Word("To begin, to start", "an|fangen", example="Der Film fängt um acht Uhr an."),
        Word("To sleep in", "sich aus|schlafen", example="Am Wochenende schlafe ich mich immer aus."),
        Word("To go out", "aus|gehen", example="Am Freitag gehen wir mit Freunden aus."),
        Word("To drive back", "zurück|fahren", example="Wir sind sofort zum Flughafen zurückgefahren."),
        Word("To take along", "etwas mit|nehmen", example="Vergiss nicht, deinen Regenschirm mitzunehmen."),
        Word("To set off, to depart", "los|fahren", example="Wir sind um sechs Uhr morgens losgefahren."),

        # --- untrennbar ---
        Word("To order (food, etc.)", "etwas bestellen", example="Ich bestelle heute Pizza."),
        Word("To forbid", "jemandem etwas verbieten", example="Meine Eltern haben mir das Rauchen verboten."),
        Word("To recommend", "jemandem etwas empfehlen", example="Kannst du mir ein gutes Restaurant empfehlen?"),
        Word("To pay", "etwas bezahlen", example="Ich habe die Rechnung schon bezahlt."),
        Word("To tell (a story)", "etwas erzählen", example="Erzähl mir, wie dein Tag war."),
        Word("To decide", "sich entscheiden", example="Ich habe mich entschieden, die Stelle anzunehmen."),
        Word("To try", "etwas versuchen", example="Ich versuche, pünktlich zu sein."),
        Word("To explain", "etwas erklären", example="Kannst du mir die Aufgabe erklären?"),
        Word("To understand", "etwas verstehen", example="Ich verstehe die Frage nicht."),
        Word("To relax (oneself)", "sich entspannen", example="Am Wochenende entspanne ich mich am liebsten zu Hause."),
        Word("To apply (for something)", "sich (um etwas) bewerben", example="Sie hat sich um die Stelle beworben."),
        Word("To go on a trip, to travel", "verreisen", example="Nächste Woche verreisen wir für zehn Tage."),
        Word("To recover, to relax", "sich erholen", example="Nach der Krankheit muss er sich noch erholen."),
        Word("To visit, to go sightseeing", "etwas besichtigen", example="Wir haben gestern das Schloss besichtigt."),
        Word("To miss (a train, flight)", "etwas verpassen", example="Ich habe leider den Zug verpasst."),
    ],

}